// Code generated by protoc-gen-go. DO NOT EDIT.
// source: operations.proto

package protocols

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OperationID struct {
	Era                  uint32   `protobuf:"varint,1,opt,name=era,proto3" json:"era,omitempty"`
	Lamport              uint64   `protobuf:"varint,2,opt,name=lamport,proto3" json:"lamport,omitempty"`
	Cuid                 []byte   `protobuf:"bytes,3,opt,name=cuid,proto3" json:"cuid,omitempty"`
	Seq                  uint64   `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperationID) Reset()         { *m = OperationID{} }
func (m *OperationID) String() string { return proto.CompactTextString(m) }
func (*OperationID) ProtoMessage()    {}
func (*OperationID) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b4a5877375e491e, []int{0}
}

func (m *OperationID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperationID.Unmarshal(m, b)
}
func (m *OperationID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperationID.Marshal(b, m, deterministic)
}
func (m *OperationID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperationID.Merge(m, src)
}
func (m *OperationID) XXX_Size() int {
	return xxx_messageInfo_OperationID.Size(m)
}
func (m *OperationID) XXX_DiscardUnknown() {
	xxx_messageInfo_OperationID.DiscardUnknown(m)
}

var xxx_messageInfo_OperationID proto.InternalMessageInfo

func (m *OperationID) GetEra() uint32 {
	if m != nil {
		return m.Era
	}
	return 0
}

func (m *OperationID) GetLamport() uint64 {
	if m != nil {
		return m.Lamport
	}
	return 0
}

func (m *OperationID) GetCuid() []byte {
	if m != nil {
		return m.Cuid
	}
	return nil
}

func (m *OperationID) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type PbOperation struct {
	Id                   *OperationID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OpType               uint32       `protobuf:"varint,2,opt,name=opType,proto3" json:"opType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PbOperation) Reset()         { *m = PbOperation{} }
func (m *PbOperation) String() string { return proto.CompactTextString(m) }
func (*PbOperation) ProtoMessage()    {}
func (*PbOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b4a5877375e491e, []int{1}
}

func (m *PbOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbOperation.Unmarshal(m, b)
}
func (m *PbOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbOperation.Marshal(b, m, deterministic)
}
func (m *PbOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbOperation.Merge(m, src)
}
func (m *PbOperation) XXX_Size() int {
	return xxx_messageInfo_PbOperation.Size(m)
}
func (m *PbOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_PbOperation.DiscardUnknown(m)
}

var xxx_messageInfo_PbOperation proto.InternalMessageInfo

func (m *PbOperation) GetId() *OperationID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *PbOperation) GetOpType() uint32 {
	if m != nil {
		return m.OpType
	}
	return 0
}

type PbIncreaseOperation struct {
	Base                 *PbOperation `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Delta                int32        `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PbIncreaseOperation) Reset()         { *m = PbIncreaseOperation{} }
func (m *PbIncreaseOperation) String() string { return proto.CompactTextString(m) }
func (*PbIncreaseOperation) ProtoMessage()    {}
func (*PbIncreaseOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b4a5877375e491e, []int{2}
}

func (m *PbIncreaseOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbIncreaseOperation.Unmarshal(m, b)
}
func (m *PbIncreaseOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbIncreaseOperation.Marshal(b, m, deterministic)
}
func (m *PbIncreaseOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbIncreaseOperation.Merge(m, src)
}
func (m *PbIncreaseOperation) XXX_Size() int {
	return xxx_messageInfo_PbIncreaseOperation.Size(m)
}
func (m *PbIncreaseOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_PbIncreaseOperation.DiscardUnknown(m)
}

var xxx_messageInfo_PbIncreaseOperation proto.InternalMessageInfo

func (m *PbIncreaseOperation) GetBase() *PbOperation {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *PbIncreaseOperation) GetDelta() int32 {
	if m != nil {
		return m.Delta
	}
	return 0
}

func init() {
	proto.RegisterType((*OperationID)(nil), "protocols.OperationID")
	proto.RegisterType((*PbOperation)(nil), "protocols.PbOperation")
	proto.RegisterType((*PbIncreaseOperation)(nil), "protocols.PbIncreaseOperation")
}

func init() { proto.RegisterFile("operations.proto", fileDescriptor_1b4a5877375e491e) }

var fileDescriptor_1b4a5877375e491e = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xe5, 0xd4, 0x2d, 0xe2, 0x42, 0xa5, 0xea, 0x40, 0x95, 0xc7, 0x28, 0x03, 0x8a, 0x18,
	0x32, 0xc0, 0x5f, 0x60, 0xe9, 0x80, 0xa8, 0x2c, 0x24, 0x46, 0x64, 0xc7, 0x37, 0x58, 0x0a, 0xb5,
	0xb1, 0xcd, 0xc0, 0xbf, 0x47, 0x39, 0x68, 0xc8, 0xc0, 0xe4, 0xf7, 0xe4, 0x7b, 0xdf, 0x7b, 0xb0,
	0x0b, 0x91, 0x92, 0x29, 0x3e, 0x9c, 0x72, 0x1f, 0x53, 0x28, 0x01, 0x2f, 0xf9, 0x19, 0xc2, 0x98,
	0xdb, 0x37, 0xa8, 0x9f, 0xcf, 0xdf, 0x87, 0x47, 0xdc, 0xc1, 0x8a, 0x92, 0x51, 0xa2, 0x11, 0xdd,
	0x56, 0x4f, 0x12, 0x15, 0x5c, 0x8c, 0xe6, 0x3d, 0x86, 0x54, 0x54, 0xd5, 0x88, 0x4e, 0xea, 0xb3,
	0x45, 0x04, 0x39, 0x7c, 0x7a, 0xa7, 0x56, 0x8d, 0xe8, 0xae, 0x34, 0xeb, 0x29, 0x9f, 0xe9, 0x43,
	0x49, 0xbe, 0x9c, 0x64, 0xfb, 0x04, 0xf5, 0xd1, 0xce, 0x15, 0x78, 0x0b, 0x95, 0x77, 0xcc, 0xaf,
	0xef, 0xf7, 0xfd, 0xbc, 0xa3, 0x5f, 0x8c, 0xd0, 0x95, 0x77, 0xb8, 0x87, 0x4d, 0x88, 0x2f, 0x5f,
	0x91, 0xb8, 0x75, 0xab, 0x7f, 0x5d, 0xfb, 0x0a, 0xd7, 0x47, 0x7b, 0x38, 0x0d, 0x89, 0x4c, 0xa6,
	0x3f, 0xec, 0x1d, 0x48, 0x6b, 0x32, 0xfd, 0x03, 0x5e, 0x94, 0x6b, 0xbe, 0xc1, 0x1b, 0x58, 0x3b,
	0x1a, 0x8b, 0x61, 0xf2, 0x5a, 0xff, 0x18, 0xbb, 0xe1, 0xc8, 0xc3, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x09, 0xb5, 0x48, 0x26, 0x2e, 0x01, 0x00, 0x00,
}
