// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: model.proto

package model

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	types "github.com/gogo/protobuf/types"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TypeOfSync int32

const (
	TypeOfSync_MANUALLY     TypeOfSync = 0
	TypeOfSync_INSTANTLY_WS TypeOfSync = 1
)

var TypeOfSync_name = map[int32]string{
	0: "MANUALLY",
	1: "INSTANTLY_WS",
}

var TypeOfSync_value = map[string]int32{
	"MANUALLY":     0,
	"INSTANTLY_WS": 1,
}

func (x TypeOfSync) String() string {
	return proto.EnumName(TypeOfSync_name, int32(x))
}

func (TypeOfSync) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

type TypeOfOperation int32

const (
	TypeOfOperation_SNAPSHOT             TypeOfOperation = 0
	TypeOfOperation_DELETE               TypeOfOperation = 1
	TypeOfOperation_ERROR                TypeOfOperation = 2
	TypeOfOperation_TRANSACTION          TypeOfOperation = 3
	TypeOfOperation_INT_COUNTER_INCREASE TypeOfOperation = 11
)

var TypeOfOperation_name = map[int32]string{
	0:  "SNAPSHOT",
	1:  "DELETE",
	2:  "ERROR",
	3:  "TRANSACTION",
	11: "INT_COUNTER_INCREASE",
}

var TypeOfOperation_value = map[string]int32{
	"SNAPSHOT":             0,
	"DELETE":               1,
	"ERROR":                2,
	"TRANSACTION":          3,
	"INT_COUNTER_INCREASE": 11,
}

func (x TypeOfOperation) String() string {
	return proto.EnumName(TypeOfOperation_name, int32(x))
}

func (TypeOfOperation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

type TypeOfDatatype int32

const (
	TypeOfDatatype_INT_COUNTER TypeOfDatatype = 0
	TypeOfDatatype_JSON        TypeOfDatatype = 1
)

var TypeOfDatatype_name = map[int32]string{
	0: "INT_COUNTER",
	1: "JSON",
}

var TypeOfDatatype_value = map[string]int32{
	"INT_COUNTER": 0,
	"JSON":        1,
}

func (x TypeOfDatatype) String() string {
	return proto.EnumName(TypeOfDatatype_name, int32(x))
}

func (TypeOfDatatype) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}

type StateOfDatatype int32

const (
	StateOfDatatype_DUE_TO_CREATE           StateOfDatatype = 0
	StateOfDatatype_DUE_TO_SUBSCRIBE        StateOfDatatype = 1
	StateOfDatatype_DUE_TO_SUBSCRIBE_CREATE StateOfDatatype = 2
	StateOfDatatype_SUBSCRIBED              StateOfDatatype = 4
	StateOfDatatype_DUE_TO_UNSUBSCRIBE      StateOfDatatype = 5
	StateOfDatatype_UNSUBSCRIBED            StateOfDatatype = 6
	StateOfDatatype_DELETED                 StateOfDatatype = 7
)

var StateOfDatatype_name = map[int32]string{
	0: "DUE_TO_CREATE",
	1: "DUE_TO_SUBSCRIBE",
	2: "DUE_TO_SUBSCRIBE_CREATE",
	4: "SUBSCRIBED",
	5: "DUE_TO_UNSUBSCRIBE",
	6: "UNSUBSCRIBED",
	7: "DELETED",
}

var StateOfDatatype_value = map[string]int32{
	"DUE_TO_CREATE":           0,
	"DUE_TO_SUBSCRIBE":        1,
	"DUE_TO_SUBSCRIBE_CREATE": 2,
	"SUBSCRIBED":              4,
	"DUE_TO_UNSUBSCRIBE":      5,
	"UNSUBSCRIBED":            6,
	"DELETED":                 7,
}

func (x StateOfDatatype) String() string {
	return proto.EnumName(StateOfDatatype_name, int32(x))
}

func (StateOfDatatype) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{3}
}

type Client struct {
	CUID                 []byte     `protobuf:"bytes,1,opt,name=CUID,proto3" json:"CUID,omitempty"`
	Alias                string     `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Collection           string     `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	SyncType             TypeOfSync `protobuf:"varint,4,opt,name=syncType,proto3,enum=model.TypeOfSync" json:"syncType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}
func (m *Client) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Client.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return m.Size()
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetCUID() []byte {
	if m != nil {
		return m.CUID
	}
	return nil
}

func (m *Client) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *Client) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

func (m *Client) GetSyncType() TypeOfSync {
	if m != nil {
		return m.SyncType
	}
	return TypeOfSync_MANUALLY
}

type OperationID struct {
	Era                  uint32   `protobuf:"varint,1,opt,name=era,proto3" json:"era,omitempty"`
	Lamport              uint64   `protobuf:"varint,2,opt,name=lamport,proto3" json:"lamport,omitempty"`
	CUID                 []byte   `protobuf:"bytes,3,opt,name=CUID,proto3" json:"CUID,omitempty"`
	Seq                  uint64   `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperationID) Reset()         { *m = OperationID{} }
func (m *OperationID) String() string { return proto.CompactTextString(m) }
func (*OperationID) ProtoMessage()    {}
func (*OperationID) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}
func (m *OperationID) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OperationID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OperationID.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OperationID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperationID.Merge(m, src)
}
func (m *OperationID) XXX_Size() int {
	return m.Size()
}
func (m *OperationID) XXX_DiscardUnknown() {
	xxx_messageInfo_OperationID.DiscardUnknown(m)
}

var xxx_messageInfo_OperationID proto.InternalMessageInfo

func (m *OperationID) GetEra() uint32 {
	if m != nil {
		return m.Era
	}
	return 0
}

func (m *OperationID) GetLamport() uint64 {
	if m != nil {
		return m.Lamport
	}
	return 0
}

func (m *OperationID) GetCUID() []byte {
	if m != nil {
		return m.CUID
	}
	return nil
}

func (m *OperationID) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type BaseOperation struct {
	ID                   *OperationID    `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	OpType               TypeOfOperation `protobuf:"varint,2,opt,name=opType,proto3,enum=model.TypeOfOperation" json:"opType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BaseOperation) Reset()         { *m = BaseOperation{} }
func (m *BaseOperation) String() string { return proto.CompactTextString(m) }
func (*BaseOperation) ProtoMessage()    {}
func (*BaseOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}
func (m *BaseOperation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BaseOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BaseOperation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BaseOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseOperation.Merge(m, src)
}
func (m *BaseOperation) XXX_Size() int {
	return m.Size()
}
func (m *BaseOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseOperation.DiscardUnknown(m)
}

var xxx_messageInfo_BaseOperation proto.InternalMessageInfo

func (m *BaseOperation) GetID() *OperationID {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *BaseOperation) GetOpType() TypeOfOperation {
	if m != nil {
		return m.OpType
	}
	return TypeOfOperation_SNAPSHOT
}

type SnapshotOperation struct {
	Base                 *BaseOperation  `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Type                 TypeOfDatatype  `protobuf:"varint,2,opt,name=type,proto3,enum=model.TypeOfDatatype" json:"type,omitempty"`
	State                StateOfDatatype `protobuf:"varint,3,opt,name=state,proto3,enum=model.StateOfDatatype" json:"state,omitempty"`
	Snapshot             *types.Any      `protobuf:"bytes,4,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SnapshotOperation) Reset()         { *m = SnapshotOperation{} }
func (m *SnapshotOperation) String() string { return proto.CompactTextString(m) }
func (*SnapshotOperation) ProtoMessage()    {}
func (*SnapshotOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{3}
}
func (m *SnapshotOperation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SnapshotOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SnapshotOperation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SnapshotOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotOperation.Merge(m, src)
}
func (m *SnapshotOperation) XXX_Size() int {
	return m.Size()
}
func (m *SnapshotOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotOperation.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotOperation proto.InternalMessageInfo

func (m *SnapshotOperation) GetBase() *BaseOperation {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *SnapshotOperation) GetType() TypeOfDatatype {
	if m != nil {
		return m.Type
	}
	return TypeOfDatatype_INT_COUNTER
}

func (m *SnapshotOperation) GetState() StateOfDatatype {
	if m != nil {
		return m.State
	}
	return StateOfDatatype_DUE_TO_CREATE
}

func (m *SnapshotOperation) GetSnapshot() *types.Any {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

type IncreaseOperation struct {
	Base                 *BaseOperation `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Delta                int32          `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *IncreaseOperation) Reset()         { *m = IncreaseOperation{} }
func (m *IncreaseOperation) String() string { return proto.CompactTextString(m) }
func (*IncreaseOperation) ProtoMessage()    {}
func (*IncreaseOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{4}
}
func (m *IncreaseOperation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IncreaseOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IncreaseOperation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IncreaseOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncreaseOperation.Merge(m, src)
}
func (m *IncreaseOperation) XXX_Size() int {
	return m.Size()
}
func (m *IncreaseOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_IncreaseOperation.DiscardUnknown(m)
}

var xxx_messageInfo_IncreaseOperation proto.InternalMessageInfo

func (m *IncreaseOperation) GetBase() *BaseOperation {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *IncreaseOperation) GetDelta() int32 {
	if m != nil {
		return m.Delta
	}
	return 0
}

type TransactionOperation struct {
	Base                 *BaseOperation `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Uuid                 []byte         `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Tag                  string         `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	NumOfOps             uint32         `protobuf:"varint,4,opt,name=numOfOps,proto3" json:"numOfOps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TransactionOperation) Reset()         { *m = TransactionOperation{} }
func (m *TransactionOperation) String() string { return proto.CompactTextString(m) }
func (*TransactionOperation) ProtoMessage()    {}
func (*TransactionOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{5}
}
func (m *TransactionOperation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TransactionOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TransactionOperation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TransactionOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionOperation.Merge(m, src)
}
func (m *TransactionOperation) XXX_Size() int {
	return m.Size()
}
func (m *TransactionOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionOperation.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionOperation proto.InternalMessageInfo

func (m *TransactionOperation) GetBase() *BaseOperation {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *TransactionOperation) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *TransactionOperation) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *TransactionOperation) GetNumOfOps() uint32 {
	if m != nil {
		return m.NumOfOps
	}
	return 0
}

type OperationOnWire struct {
	// Types that are valid to be assigned to Body:
	//	*OperationOnWire_Snapshot
	//	*OperationOnWire_Transaction
	//	*OperationOnWire_Increase
	Body                 isOperationOnWire_Body `protobuf_oneof:"body"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *OperationOnWire) Reset()         { *m = OperationOnWire{} }
func (m *OperationOnWire) String() string { return proto.CompactTextString(m) }
func (*OperationOnWire) ProtoMessage()    {}
func (*OperationOnWire) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{6}
}
func (m *OperationOnWire) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OperationOnWire) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OperationOnWire.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OperationOnWire) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperationOnWire.Merge(m, src)
}
func (m *OperationOnWire) XXX_Size() int {
	return m.Size()
}
func (m *OperationOnWire) XXX_DiscardUnknown() {
	xxx_messageInfo_OperationOnWire.DiscardUnknown(m)
}

var xxx_messageInfo_OperationOnWire proto.InternalMessageInfo

type isOperationOnWire_Body interface {
	isOperationOnWire_Body()
	MarshalTo([]byte) (int, error)
	Size() int
}

type OperationOnWire_Snapshot struct {
	Snapshot *SnapshotOperation `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof" json:"snapshot,omitempty"`
}
type OperationOnWire_Transaction struct {
	Transaction *TransactionOperation `protobuf:"bytes,5,opt,name=transaction,proto3,oneof" json:"transaction,omitempty"`
}
type OperationOnWire_Increase struct {
	Increase *IncreaseOperation `protobuf:"bytes,11,opt,name=increase,proto3,oneof" json:"increase,omitempty"`
}

func (*OperationOnWire_Snapshot) isOperationOnWire_Body()    {}
func (*OperationOnWire_Transaction) isOperationOnWire_Body() {}
func (*OperationOnWire_Increase) isOperationOnWire_Body()    {}

func (m *OperationOnWire) GetBody() isOperationOnWire_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *OperationOnWire) GetSnapshot() *SnapshotOperation {
	if x, ok := m.GetBody().(*OperationOnWire_Snapshot); ok {
		return x.Snapshot
	}
	return nil
}

func (m *OperationOnWire) GetTransaction() *TransactionOperation {
	if x, ok := m.GetBody().(*OperationOnWire_Transaction); ok {
		return x.Transaction
	}
	return nil
}

func (m *OperationOnWire) GetIncrease() *IncreaseOperation {
	if x, ok := m.GetBody().(*OperationOnWire_Increase); ok {
		return x.Increase
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*OperationOnWire) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*OperationOnWire_Snapshot)(nil),
		(*OperationOnWire_Transaction)(nil),
		(*OperationOnWire_Increase)(nil),
	}
}

type PushPullPack struct {
	DUID                 []byte             `protobuf:"bytes,1,opt,name=DUID,proto3" json:"DUID,omitempty"`
	Key                  string             `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Option               uint32             `protobuf:"fixed32,3,opt,name=option,proto3" json:"option,omitempty"`
	CheckPoint           *CheckPoint        `protobuf:"bytes,4,opt,name=checkPoint,proto3" json:"checkPoint,omitempty"`
	Era                  uint32             `protobuf:"varint,5,opt,name=era,proto3" json:"era,omitempty"`
	Type                 int32              `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	Operations           []*OperationOnWire `protobuf:"bytes,7,rep,name=operations,proto3" json:"operations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PushPullPack) Reset()         { *m = PushPullPack{} }
func (m *PushPullPack) String() string { return proto.CompactTextString(m) }
func (*PushPullPack) ProtoMessage()    {}
func (*PushPullPack) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{7}
}
func (m *PushPullPack) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PushPullPack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PushPullPack.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PushPullPack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushPullPack.Merge(m, src)
}
func (m *PushPullPack) XXX_Size() int {
	return m.Size()
}
func (m *PushPullPack) XXX_DiscardUnknown() {
	xxx_messageInfo_PushPullPack.DiscardUnknown(m)
}

var xxx_messageInfo_PushPullPack proto.InternalMessageInfo

func (m *PushPullPack) GetDUID() []byte {
	if m != nil {
		return m.DUID
	}
	return nil
}

func (m *PushPullPack) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PushPullPack) GetOption() uint32 {
	if m != nil {
		return m.Option
	}
	return 0
}

func (m *PushPullPack) GetCheckPoint() *CheckPoint {
	if m != nil {
		return m.CheckPoint
	}
	return nil
}

func (m *PushPullPack) GetEra() uint32 {
	if m != nil {
		return m.Era
	}
	return 0
}

func (m *PushPullPack) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *PushPullPack) GetOperations() []*OperationOnWire {
	if m != nil {
		return m.Operations
	}
	return nil
}

type CheckPoint struct {
	// @inject_tag: bson:"s"
	Sseq uint64 `protobuf:"varint,1,opt,name=sseq,json=s,proto3" json:"sseq,omitempty" bson:"s"`
	// @inject_tag: bson:"c"
	Cseq                 uint64   `protobuf:"varint,2,opt,name=cseq,json=c,proto3" json:"cseq,omitempty" bson:"c"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPoint) Reset()         { *m = CheckPoint{} }
func (m *CheckPoint) String() string { return proto.CompactTextString(m) }
func (*CheckPoint) ProtoMessage()    {}
func (*CheckPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{8}
}
func (m *CheckPoint) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CheckPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CheckPoint.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CheckPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPoint.Merge(m, src)
}
func (m *CheckPoint) XXX_Size() int {
	return m.Size()
}
func (m *CheckPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPoint.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPoint proto.InternalMessageInfo

func (m *CheckPoint) GetSseq() uint64 {
	if m != nil {
		return m.Sseq
	}
	return 0
}

func (m *CheckPoint) GetCseq() uint64 {
	if m != nil {
		return m.Cseq
	}
	return 0
}

type DatatypeMeta struct {
	Key                  string          `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	DUID                 []byte          `protobuf:"bytes,2,opt,name=DUID,proto3" json:"DUID,omitempty"`
	OpID                 *OperationID    `protobuf:"bytes,3,opt,name=opID,proto3" json:"opID,omitempty"`
	TypeOf               TypeOfDatatype  `protobuf:"varint,4,opt,name=typeOf,proto3,enum=model.TypeOfDatatype" json:"typeOf,omitempty"`
	State                StateOfDatatype `protobuf:"varint,5,opt,name=state,proto3,enum=model.StateOfDatatype" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DatatypeMeta) Reset()         { *m = DatatypeMeta{} }
func (m *DatatypeMeta) String() string { return proto.CompactTextString(m) }
func (*DatatypeMeta) ProtoMessage()    {}
func (*DatatypeMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{9}
}
func (m *DatatypeMeta) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DatatypeMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DatatypeMeta.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DatatypeMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatatypeMeta.Merge(m, src)
}
func (m *DatatypeMeta) XXX_Size() int {
	return m.Size()
}
func (m *DatatypeMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_DatatypeMeta.DiscardUnknown(m)
}

var xxx_messageInfo_DatatypeMeta proto.InternalMessageInfo

func (m *DatatypeMeta) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DatatypeMeta) GetDUID() []byte {
	if m != nil {
		return m.DUID
	}
	return nil
}

func (m *DatatypeMeta) GetOpID() *OperationID {
	if m != nil {
		return m.OpID
	}
	return nil
}

func (m *DatatypeMeta) GetTypeOf() TypeOfDatatype {
	if m != nil {
		return m.TypeOf
	}
	return TypeOfDatatype_INT_COUNTER
}

func (m *DatatypeMeta) GetState() StateOfDatatype {
	if m != nil {
		return m.State
	}
	return StateOfDatatype_DUE_TO_CREATE
}

func init() {
	proto.RegisterEnum("model.TypeOfSync", TypeOfSync_name, TypeOfSync_value)
	proto.RegisterEnum("model.TypeOfOperation", TypeOfOperation_name, TypeOfOperation_value)
	proto.RegisterEnum("model.TypeOfDatatype", TypeOfDatatype_name, TypeOfDatatype_value)
	proto.RegisterEnum("model.StateOfDatatype", StateOfDatatype_name, StateOfDatatype_value)
	proto.RegisterType((*Client)(nil), "model.Client")
	proto.RegisterType((*OperationID)(nil), "model.OperationID")
	proto.RegisterType((*BaseOperation)(nil), "model.BaseOperation")
	proto.RegisterType((*SnapshotOperation)(nil), "model.SnapshotOperation")
	proto.RegisterType((*IncreaseOperation)(nil), "model.IncreaseOperation")
	proto.RegisterType((*TransactionOperation)(nil), "model.TransactionOperation")
	proto.RegisterType((*OperationOnWire)(nil), "model.OperationOnWire")
	proto.RegisterType((*PushPullPack)(nil), "model.PushPullPack")
	proto.RegisterType((*CheckPoint)(nil), "model.CheckPoint")
	proto.RegisterType((*DatatypeMeta)(nil), "model.DatatypeMeta")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 875 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0xd6, 0x4a, 0xa4, 0xac, 0x8c, 0x64, 0x6b, 0x3d, 0x50, 0x5d, 0x36, 0x01, 0x04, 0x83, 0x87,
	0x42, 0x75, 0x13, 0xa5, 0x4d, 0x81, 0x5c, 0x0b, 0x49, 0x24, 0x60, 0x16, 0x0e, 0x29, 0x2c, 0x29,
	0x04, 0x39, 0x09, 0x6b, 0x9a, 0xb1, 0x05, 0xd3, 0xa4, 0x2a, 0x52, 0x07, 0x1d, 0xdb, 0xa7, 0xe8,
	0xa9, 0xef, 0xd1, 0x37, 0x08, 0x7a, 0xea, 0x0b, 0x14, 0x28, 0xdc, 0x17, 0x29, 0x76, 0xf9, 0x2b,
	0x35, 0x05, 0x82, 0xde, 0x76, 0x67, 0xbf, 0xdd, 0xf9, 0xbe, 0xd9, 0xf9, 0x06, 0xba, 0x0f, 0xf1,
	0x4d, 0x10, 0x8e, 0xd7, 0x9b, 0x38, 0x8d, 0x51, 0x95, 0x9b, 0xa7, 0x5f, 0xdc, 0xc6, 0xf1, 0x6d,
	0x18, 0xbc, 0x94, 0xc1, 0xeb, 0xed, 0xfb, 0x97, 0x3c, 0xda, 0x65, 0x08, 0xfd, 0x27, 0x02, 0xed,
	0x59, 0xb8, 0x0a, 0xa2, 0x14, 0x11, 0x94, 0xd9, 0xc2, 0x32, 0x34, 0x72, 0x4e, 0x46, 0x3d, 0x26,
	0xd7, 0x38, 0x00, 0x95, 0x87, 0x2b, 0x9e, 0x68, 0xcd, 0x73, 0x32, 0x7a, 0xc2, 0xb2, 0x0d, 0x0e,
	0x01, 0xfc, 0x38, 0x0c, 0x03, 0x3f, 0x5d, 0xc5, 0x91, 0xd6, 0x92, 0x47, 0xb5, 0x08, 0xbe, 0x80,
	0x4e, 0xb2, 0x8b, 0x7c, 0x6f, 0xb7, 0x0e, 0x34, 0xe5, 0x9c, 0x8c, 0x4e, 0x5e, 0x9d, 0x8e, 0x33,
	0x5a, 0x22, 0xe4, 0xbc, 0x77, 0x77, 0x91, 0xcf, 0x4a, 0x88, 0xbe, 0x84, 0xae, 0xb3, 0x0e, 0x36,
	0x5c, 0xdc, 0xb5, 0x0c, 0xa4, 0xd0, 0x0a, 0x36, 0x5c, 0xd2, 0x38, 0x66, 0x62, 0x89, 0x1a, 0x1c,
	0x85, 0xfc, 0x61, 0x1d, 0x6f, 0x52, 0xc9, 0x43, 0x61, 0xc5, 0xb6, 0xe4, 0xdc, 0xaa, 0x71, 0xa6,
	0xd0, 0x4a, 0x82, 0x1f, 0x65, 0x62, 0x85, 0x89, 0xa5, 0xee, 0xc3, 0xf1, 0x94, 0x27, 0x41, 0x99,
	0x04, 0x75, 0x68, 0xe6, 0x42, 0xbb, 0xaf, 0x30, 0xa7, 0x56, 0xa3, 0xc0, 0x9a, 0x96, 0x81, 0x63,
	0x68, 0xc7, 0x6b, 0x29, 0xa1, 0x29, 0x25, 0x9c, 0xed, 0x49, 0x28, 0xd1, 0x2c, 0x47, 0xe9, 0x1f,
	0x08, 0x9c, 0xba, 0x11, 0x5f, 0x27, 0x77, 0x71, 0x5a, 0x65, 0x1a, 0x81, 0x72, 0xcd, 0x93, 0x20,
	0xcf, 0x35, 0xc8, 0xdf, 0xd8, 0x63, 0xc3, 0x24, 0x02, 0xbf, 0x02, 0x25, 0xad, 0xb2, 0x7d, 0xb6,
	0x97, 0xcd, 0xe0, 0x29, 0x17, 0x87, 0x4c, 0x42, 0xf0, 0x39, 0xa8, 0x49, 0xca, 0xd3, 0x40, 0xca,
	0xae, 0x98, 0xb9, 0x22, 0x56, 0x03, 0x67, 0x20, 0xfc, 0x06, 0x3a, 0x49, 0xce, 0x4b, 0x16, 0x45,
	0xd0, 0xc8, 0x1a, 0x62, 0x5c, 0x34, 0xc4, 0x78, 0x12, 0xed, 0x58, 0x89, 0xd2, 0x5d, 0x38, 0xb5,
	0x22, 0x7f, 0x13, 0xec, 0xd5, 0xec, 0xd3, 0x95, 0x0c, 0x40, 0xbd, 0x09, 0xc2, 0x94, 0x4b, 0x29,
	0x2a, 0xcb, 0x36, 0xfa, 0xcf, 0x04, 0x06, 0xde, 0x86, 0x47, 0x09, 0x97, 0x4d, 0xf2, 0x7f, 0x1e,
	0x46, 0x50, 0xb6, 0xdb, 0xd5, 0x8d, 0x7c, 0xb7, 0xc7, 0xe4, 0x5a, 0xfc, 0x76, 0xca, 0x6f, 0xf3,
	0x26, 0x14, 0x4b, 0x7c, 0x0a, 0x9d, 0x68, 0xfb, 0x20, 0xbe, 0x28, 0x91, 0x7a, 0x8f, 0x59, 0xb9,
	0xd7, 0x7f, 0x27, 0xd0, 0x2f, 0x5f, 0x75, 0xa2, 0xb7, 0xab, 0x4d, 0x80, 0xaf, 0x6b, 0xf5, 0xc9,
	0x38, 0x68, 0x45, 0x41, 0x0f, 0xbf, 0xf3, 0xb2, 0x51, 0x55, 0x09, 0xbf, 0x87, 0x6e, 0x5a, 0xe9,
	0xd1, 0x54, 0x79, 0xf5, 0x59, 0xf1, 0x6f, 0x1f, 0x51, 0x7a, 0xd9, 0x60, 0xf5, 0x1b, 0x22, 0xf1,
	0x2a, 0x2f, 0xb3, 0xd6, 0xdd, 0x4b, 0xfc, 0xaf, 0xea, 0x8b, 0xc4, 0x05, 0x76, 0xda, 0x06, 0xe5,
	0x3a, 0xbe, 0xd9, 0xe9, 0x7f, 0x12, 0xe8, 0xcd, 0xb7, 0xc9, 0xdd, 0x7c, 0x1b, 0x86, 0x73, 0xee,
	0xdf, 0x8b, 0xfa, 0x18, 0x35, 0x07, 0x1b, 0xb9, 0x1b, 0xee, 0x83, 0x5d, 0xee, 0x5f, 0xb1, 0xc4,
	0x33, 0xd1, 0xd8, 0xa5, 0x73, 0x8f, 0x58, 0xbe, 0xc3, 0x6f, 0x01, 0xfc, 0xbb, 0xc0, 0xbf, 0x9f,
	0xc7, 0xab, 0xa8, 0xe8, 0x94, 0xc2, 0xb7, 0xb3, 0xf2, 0x80, 0xd5, 0x40, 0x85, 0x55, 0xd5, 0xca,
	0xaa, 0x98, 0x77, 0x71, 0x5b, 0x7e, 0x7d, 0xd6, 0xae, 0xaf, 0x01, 0xe2, 0x42, 0x48, 0xa2, 0x1d,
	0x9d, 0xb7, 0x46, 0xdd, 0xb2, 0x67, 0x0f, 0x3e, 0x83, 0xd5, 0x90, 0xfa, 0x18, 0xa0, 0xca, 0x8b,
	0x7d, 0x50, 0x12, 0xe1, 0x6b, 0x22, 0x7d, 0x4d, 0x12, 0x11, 0xf0, 0x45, 0x20, 0x1b, 0x09, 0xc4,
	0xd7, 0x7f, 0x23, 0xd0, 0x2b, 0x9a, 0xff, 0x4d, 0x90, 0xf2, 0x42, 0x3b, 0xa9, 0xb4, 0x17, 0x15,
	0x6a, 0xd6, 0x2a, 0xf4, 0x25, 0x28, 0xf1, 0x3a, 0x9f, 0x21, 0x1f, 0x1f, 0x07, 0xf2, 0x1c, 0x5f,
	0x40, 0x3b, 0x95, 0x6e, 0xcc, 0x67, 0xda, 0x7f, 0x58, 0x34, 0x07, 0x55, 0x26, 0x55, 0x3f, 0xc1,
	0xa4, 0x17, 0xcf, 0x01, 0xaa, 0xd9, 0x88, 0x3d, 0xe8, 0xbc, 0x99, 0xd8, 0x8b, 0xc9, 0xd5, 0xd5,
	0x3b, 0xda, 0x40, 0x0a, 0x3d, 0xcb, 0x76, 0xbd, 0x89, 0xed, 0x5d, 0xbd, 0x5b, 0xbe, 0x75, 0x29,
	0xb9, 0xe0, 0xd0, 0x3f, 0x18, 0x43, 0xe2, 0x8a, 0x6b, 0x4f, 0xe6, 0xee, 0xa5, 0xe3, 0xd1, 0x06,
	0x02, 0xb4, 0x0d, 0xf3, 0xca, 0xf4, 0x4c, 0x4a, 0xf0, 0x09, 0xa8, 0x26, 0x63, 0x0e, 0xa3, 0x4d,
	0xec, 0x43, 0xd7, 0x63, 0x13, 0xdb, 0x9d, 0xcc, 0x3c, 0xcb, 0xb1, 0x69, 0x0b, 0x35, 0x18, 0x58,
	0xb6, 0xb7, 0x9c, 0x39, 0x0b, 0xdb, 0x33, 0xd9, 0xd2, 0xb2, 0x67, 0xcc, 0x9c, 0xb8, 0x26, 0xed,
	0x5e, 0x7c, 0x0d, 0x27, 0xfb, 0xc2, 0xc4, 0xe5, 0x1a, 0x96, 0x36, 0xb0, 0x03, 0xca, 0x0f, 0xae,
	0x63, 0x53, 0x72, 0xf1, 0x2b, 0x81, 0xfe, 0x81, 0x30, 0x3c, 0x85, 0x63, 0x63, 0x61, 0x2e, 0x3d,
	0x67, 0x29, 0xde, 0xf4, 0x4c, 0xda, 0xc0, 0x01, 0xd0, 0x3c, 0xe4, 0x2e, 0xa6, 0xee, 0x8c, 0x59,
	0x53, 0xc1, 0xef, 0x19, 0x7c, 0x7e, 0x18, 0x2d, 0xae, 0x34, 0xf1, 0x04, 0xa0, 0x8c, 0x1a, 0x54,
	0xc1, 0x33, 0xc0, 0x1c, 0xbc, 0xb0, 0xab, 0x47, 0x54, 0x51, 0xa3, 0x5a, 0xc0, 0xa0, 0x6d, 0xec,
	0xc2, 0x51, 0x56, 0x02, 0x83, 0x1e, 0x4d, 0xe9, 0x87, 0xc7, 0x21, 0xf9, 0xe3, 0x71, 0x48, 0xfe,
	0x7a, 0x1c, 0x92, 0x5f, 0xfe, 0x1e, 0x36, 0xae, 0xdb, 0x72, 0xf6, 0x7d, 0xf7, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x82, 0x12, 0x43, 0x85, 0x30, 0x07, 0x00, 0x00,
}

func (m *Client) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Client) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Client) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.SyncType != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.SyncType))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Collection) > 0 {
		i -= len(m.Collection)
		copy(dAtA[i:], m.Collection)
		i = encodeVarintModel(dAtA, i, uint64(len(m.Collection)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Alias) > 0 {
		i -= len(m.Alias)
		copy(dAtA[i:], m.Alias)
		i = encodeVarintModel(dAtA, i, uint64(len(m.Alias)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.CUID) > 0 {
		i -= len(m.CUID)
		copy(dAtA[i:], m.CUID)
		i = encodeVarintModel(dAtA, i, uint64(len(m.CUID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *OperationID) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OperationID) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OperationID) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Seq != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.Seq))
		i--
		dAtA[i] = 0x20
	}
	if len(m.CUID) > 0 {
		i -= len(m.CUID)
		copy(dAtA[i:], m.CUID)
		i = encodeVarintModel(dAtA, i, uint64(len(m.CUID)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Lamport != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.Lamport))
		i--
		dAtA[i] = 0x10
	}
	if m.Era != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.Era))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BaseOperation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BaseOperation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BaseOperation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.OpType != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.OpType))
		i--
		dAtA[i] = 0x10
	}
	if m.ID != nil {
		{
			size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintModel(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SnapshotOperation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SnapshotOperation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SnapshotOperation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Snapshot != nil {
		{
			size, err := m.Snapshot.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintModel(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.State != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x18
	}
	if m.Type != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x10
	}
	if m.Base != nil {
		{
			size, err := m.Base.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintModel(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *IncreaseOperation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IncreaseOperation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IncreaseOperation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Delta != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.Delta))
		i--
		dAtA[i] = 0x10
	}
	if m.Base != nil {
		{
			size, err := m.Base.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintModel(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TransactionOperation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TransactionOperation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TransactionOperation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.NumOfOps != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.NumOfOps))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Tag) > 0 {
		i -= len(m.Tag)
		copy(dAtA[i:], m.Tag)
		i = encodeVarintModel(dAtA, i, uint64(len(m.Tag)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Uuid) > 0 {
		i -= len(m.Uuid)
		copy(dAtA[i:], m.Uuid)
		i = encodeVarintModel(dAtA, i, uint64(len(m.Uuid)))
		i--
		dAtA[i] = 0x12
	}
	if m.Base != nil {
		{
			size, err := m.Base.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintModel(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *OperationOnWire) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OperationOnWire) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OperationOnWire) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Body != nil {
		{
			size := m.Body.Size()
			i -= size
			if _, err := m.Body.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *OperationOnWire_Snapshot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OperationOnWire_Snapshot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Snapshot != nil {
		{
			size, err := m.Snapshot.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintModel(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *OperationOnWire_Transaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OperationOnWire_Transaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Transaction != nil {
		{
			size, err := m.Transaction.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintModel(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	return len(dAtA) - i, nil
}
func (m *OperationOnWire_Increase) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OperationOnWire_Increase) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Increase != nil {
		{
			size, err := m.Increase.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintModel(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x5a
	}
	return len(dAtA) - i, nil
}
func (m *PushPullPack) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PushPullPack) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PushPullPack) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Operations) > 0 {
		for iNdEx := len(m.Operations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Operations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintModel(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.Type != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x30
	}
	if m.Era != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.Era))
		i--
		dAtA[i] = 0x28
	}
	if m.CheckPoint != nil {
		{
			size, err := m.CheckPoint.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintModel(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Option != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(m.Option))
		i--
		dAtA[i] = 0x1d
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintModel(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DUID) > 0 {
		i -= len(m.DUID)
		copy(dAtA[i:], m.DUID)
		i = encodeVarintModel(dAtA, i, uint64(len(m.DUID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CheckPoint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CheckPoint) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CheckPoint) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Cseq != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.Cseq))
		i--
		dAtA[i] = 0x10
	}
	if m.Sseq != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.Sseq))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DatatypeMeta) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DatatypeMeta) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DatatypeMeta) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.State != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x28
	}
	if m.TypeOf != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.TypeOf))
		i--
		dAtA[i] = 0x20
	}
	if m.OpID != nil {
		{
			size, err := m.OpID.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintModel(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DUID) > 0 {
		i -= len(m.DUID)
		copy(dAtA[i:], m.DUID)
		i = encodeVarintModel(dAtA, i, uint64(len(m.DUID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintModel(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintModel(dAtA []byte, offset int, v uint64) int {
	offset -= sovModel(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Client) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CUID)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	l = len(m.Alias)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	l = len(m.Collection)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	if m.SyncType != 0 {
		n += 1 + sovModel(uint64(m.SyncType))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *OperationID) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Era != 0 {
		n += 1 + sovModel(uint64(m.Era))
	}
	if m.Lamport != 0 {
		n += 1 + sovModel(uint64(m.Lamport))
	}
	l = len(m.CUID)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	if m.Seq != 0 {
		n += 1 + sovModel(uint64(m.Seq))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *BaseOperation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ID != nil {
		l = m.ID.Size()
		n += 1 + l + sovModel(uint64(l))
	}
	if m.OpType != 0 {
		n += 1 + sovModel(uint64(m.OpType))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SnapshotOperation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Base != nil {
		l = m.Base.Size()
		n += 1 + l + sovModel(uint64(l))
	}
	if m.Type != 0 {
		n += 1 + sovModel(uint64(m.Type))
	}
	if m.State != 0 {
		n += 1 + sovModel(uint64(m.State))
	}
	if m.Snapshot != nil {
		l = m.Snapshot.Size()
		n += 1 + l + sovModel(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *IncreaseOperation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Base != nil {
		l = m.Base.Size()
		n += 1 + l + sovModel(uint64(l))
	}
	if m.Delta != 0 {
		n += 1 + sovModel(uint64(m.Delta))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *TransactionOperation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Base != nil {
		l = m.Base.Size()
		n += 1 + l + sovModel(uint64(l))
	}
	l = len(m.Uuid)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	l = len(m.Tag)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	if m.NumOfOps != 0 {
		n += 1 + sovModel(uint64(m.NumOfOps))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *OperationOnWire) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Body != nil {
		n += m.Body.Size()
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *OperationOnWire_Snapshot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Snapshot != nil {
		l = m.Snapshot.Size()
		n += 1 + l + sovModel(uint64(l))
	}
	return n
}
func (m *OperationOnWire_Transaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Transaction != nil {
		l = m.Transaction.Size()
		n += 1 + l + sovModel(uint64(l))
	}
	return n
}
func (m *OperationOnWire_Increase) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Increase != nil {
		l = m.Increase.Size()
		n += 1 + l + sovModel(uint64(l))
	}
	return n
}
func (m *PushPullPack) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DUID)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	if m.Option != 0 {
		n += 5
	}
	if m.CheckPoint != nil {
		l = m.CheckPoint.Size()
		n += 1 + l + sovModel(uint64(l))
	}
	if m.Era != 0 {
		n += 1 + sovModel(uint64(m.Era))
	}
	if m.Type != 0 {
		n += 1 + sovModel(uint64(m.Type))
	}
	if len(m.Operations) > 0 {
		for _, e := range m.Operations {
			l = e.Size()
			n += 1 + l + sovModel(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *CheckPoint) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Sseq != 0 {
		n += 1 + sovModel(uint64(m.Sseq))
	}
	if m.Cseq != 0 {
		n += 1 + sovModel(uint64(m.Cseq))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *DatatypeMeta) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	l = len(m.DUID)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	if m.OpID != nil {
		l = m.OpID.Size()
		n += 1 + l + sovModel(uint64(l))
	}
	if m.TypeOf != 0 {
		n += 1 + sovModel(uint64(m.TypeOf))
	}
	if m.State != 0 {
		n += 1 + sovModel(uint64(m.State))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovModel(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozModel(x uint64) (n int) {
	return sovModel(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Client) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Client: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Client: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CUID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CUID = append(m.CUID[:0], dAtA[iNdEx:postIndex]...)
			if m.CUID == nil {
				m.CUID = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Alias", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Alias = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Collection", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Collection = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SyncType", wireType)
			}
			m.SyncType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SyncType |= TypeOfSync(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthModel
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OperationID) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OperationID: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OperationID: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Era", wireType)
			}
			m.Era = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Era |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lamport", wireType)
			}
			m.Lamport = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Lamport |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CUID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CUID = append(m.CUID[:0], dAtA[iNdEx:postIndex]...)
			if m.CUID == nil {
				m.CUID = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seq", wireType)
			}
			m.Seq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Seq |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthModel
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BaseOperation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BaseOperation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BaseOperation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ID == nil {
				m.ID = &OperationID{}
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OpType", wireType)
			}
			m.OpType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OpType |= TypeOfOperation(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthModel
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SnapshotOperation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SnapshotOperation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SnapshotOperation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Base", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Base == nil {
				m.Base = &BaseOperation{}
			}
			if err := m.Base.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= TypeOfDatatype(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= StateOfDatatype(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Snapshot", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Snapshot == nil {
				m.Snapshot = &types.Any{}
			}
			if err := m.Snapshot.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthModel
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IncreaseOperation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IncreaseOperation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IncreaseOperation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Base", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Base == nil {
				m.Base = &BaseOperation{}
			}
			if err := m.Base.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delta", wireType)
			}
			m.Delta = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Delta |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthModel
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TransactionOperation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TransactionOperation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TransactionOperation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Base", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Base == nil {
				m.Base = &BaseOperation{}
			}
			if err := m.Base.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uuid", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uuid = append(m.Uuid[:0], dAtA[iNdEx:postIndex]...)
			if m.Uuid == nil {
				m.Uuid = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tag", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tag = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumOfOps", wireType)
			}
			m.NumOfOps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumOfOps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthModel
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OperationOnWire) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OperationOnWire: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OperationOnWire: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Snapshot", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &SnapshotOperation{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Body = &OperationOnWire_Snapshot{v}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transaction", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &TransactionOperation{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Body = &OperationOnWire_Transaction{v}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Increase", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &IncreaseOperation{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Body = &OperationOnWire_Increase{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthModel
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PushPullPack) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PushPullPack: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PushPullPack: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DUID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DUID = append(m.DUID[:0], dAtA[iNdEx:postIndex]...)
			if m.DUID == nil {
				m.DUID = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Option", wireType)
			}
			m.Option = 0
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			m.Option = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CheckPoint", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CheckPoint == nil {
				m.CheckPoint = &CheckPoint{}
			}
			if err := m.CheckPoint.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Era", wireType)
			}
			m.Era = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Era |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operations = append(m.Operations, &OperationOnWire{})
			if err := m.Operations[len(m.Operations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthModel
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CheckPoint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CheckPoint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CheckPoint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sseq", wireType)
			}
			m.Sseq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sseq |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cseq", wireType)
			}
			m.Cseq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cseq |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthModel
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DatatypeMeta) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DatatypeMeta: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DatatypeMeta: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DUID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DUID = append(m.DUID[:0], dAtA[iNdEx:postIndex]...)
			if m.DUID == nil {
				m.DUID = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OpID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OpID == nil {
				m.OpID = &OperationID{}
			}
			if err := m.OpID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TypeOf", wireType)
			}
			m.TypeOf = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TypeOf |= TypeOfDatatype(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= StateOfDatatype(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthModel
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipModel(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowModel
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowModel
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowModel
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthModel
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupModel
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthModel
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthModel        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowModel          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupModel = fmt.Errorf("proto: unexpected end of group")
)
