// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TypeOfSync int32

const (
	TypeOfSync_MANUALLY     TypeOfSync = 0
	TypeOfSync_INSTANTLY_WS TypeOfSync = 1
)

var TypeOfSync_name = map[int32]string{
	0: "MANUALLY",
	1: "INSTANTLY_WS",
}

var TypeOfSync_value = map[string]int32{
	"MANUALLY":     0,
	"INSTANTLY_WS": 1,
}

func (x TypeOfSync) String() string {
	return proto.EnumName(TypeOfSync_name, int32(x))
}

func (TypeOfSync) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

type TypeOfOperation int32

const (
	TypeOfOperation_Create               TypeOfOperation = 0
	TypeOfOperation_DELETE               TypeOfOperation = 1
	TypeOfOperation_ERROR                TypeOfOperation = 2
	TypeOfOperation_SNAPSHOT             TypeOfOperation = 4
	TypeOfOperation_TRANSACTION_BEGIN    TypeOfOperation = 5
	TypeOfOperation_TRANSACTION_END      TypeOfOperation = 6
	TypeOfOperation_INT_COUNTER_INCREASE TypeOfOperation = 11
)

var TypeOfOperation_name = map[int32]string{
	0:  "Create",
	1:  "DELETE",
	2:  "ERROR",
	4:  "SNAPSHOT",
	5:  "TRANSACTION_BEGIN",
	6:  "TRANSACTION_END",
	11: "INT_COUNTER_INCREASE",
}

var TypeOfOperation_value = map[string]int32{
	"Create":               0,
	"DELETE":               1,
	"ERROR":                2,
	"SNAPSHOT":             4,
	"TRANSACTION_BEGIN":    5,
	"TRANSACTION_END":      6,
	"INT_COUNTER_INCREASE": 11,
}

func (x TypeOfOperation) String() string {
	return proto.EnumName(TypeOfOperation_name, int32(x))
}

func (TypeOfOperation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

type TypeOfDatatype int32

const (
	TypeOfDatatype_INT_COUNTER TypeOfDatatype = 0
	TypeOfDatatype_JSON        TypeOfDatatype = 1
)

var TypeOfDatatype_name = map[int32]string{
	0: "INT_COUNTER",
	1: "JSON",
}

var TypeOfDatatype_value = map[string]int32{
	"INT_COUNTER": 0,
	"JSON":        1,
}

func (x TypeOfDatatype) String() string {
	return proto.EnumName(TypeOfDatatype_name, int32(x))
}

func (TypeOfDatatype) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}

type StateOfDatatype int32

const (
	StateOfDatatype_LOCALLY_EXISTED StateOfDatatype = 0
	StateOfDatatype_REGISTERING     StateOfDatatype = 1
	StateOfDatatype_REGISTERED      StateOfDatatype = 2
	StateOfDatatype_UNREGISTERED    StateOfDatatype = 3
)

var StateOfDatatype_name = map[int32]string{
	0: "LOCALLY_EXISTED",
	1: "REGISTERING",
	2: "REGISTERED",
	3: "UNREGISTERED",
}

var StateOfDatatype_value = map[string]int32{
	"LOCALLY_EXISTED": 0,
	"REGISTERING":     1,
	"REGISTERED":      2,
	"UNREGISTERED":    3,
}

func (x StateOfDatatype) String() string {
	return proto.EnumName(StateOfDatatype_name, int32(x))
}

func (StateOfDatatype) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{3}
}

type Client struct {
	Cuid                 []byte     `protobuf:"bytes,1,opt,name=cuid,proto3" json:"cuid,omitempty"`
	Alias                string     `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Collection           string     `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	SyncType             TypeOfSync `protobuf:"varint,4,opt,name=syncType,proto3,enum=model.TypeOfSync" json:"syncType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetCuid() []byte {
	if m != nil {
		return m.Cuid
	}
	return nil
}

func (m *Client) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *Client) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

func (m *Client) GetSyncType() TypeOfSync {
	if m != nil {
		return m.SyncType
	}
	return TypeOfSync_MANUALLY
}

type OperationID struct {
	Era                  uint32   `protobuf:"varint,1,opt,name=era,proto3" json:"era,omitempty"`
	Lamport              uint64   `protobuf:"varint,2,opt,name=lamport,proto3" json:"lamport,omitempty"`
	Cuid                 []byte   `protobuf:"bytes,3,opt,name=cuid,proto3" json:"cuid,omitempty"`
	Seq                  uint64   `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperationID) Reset()         { *m = OperationID{} }
func (m *OperationID) String() string { return proto.CompactTextString(m) }
func (*OperationID) ProtoMessage()    {}
func (*OperationID) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

func (m *OperationID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperationID.Unmarshal(m, b)
}
func (m *OperationID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperationID.Marshal(b, m, deterministic)
}
func (m *OperationID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperationID.Merge(m, src)
}
func (m *OperationID) XXX_Size() int {
	return xxx_messageInfo_OperationID.Size(m)
}
func (m *OperationID) XXX_DiscardUnknown() {
	xxx_messageInfo_OperationID.DiscardUnknown(m)
}

var xxx_messageInfo_OperationID proto.InternalMessageInfo

func (m *OperationID) GetEra() uint32 {
	if m != nil {
		return m.Era
	}
	return 0
}

func (m *OperationID) GetLamport() uint64 {
	if m != nil {
		return m.Lamport
	}
	return 0
}

func (m *OperationID) GetCuid() []byte {
	if m != nil {
		return m.Cuid
	}
	return nil
}

func (m *OperationID) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type BaseOperation struct {
	Id                   *OperationID    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OpType               TypeOfOperation `protobuf:"varint,2,opt,name=opType,proto3,enum=model.TypeOfOperation" json:"opType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BaseOperation) Reset()         { *m = BaseOperation{} }
func (m *BaseOperation) String() string { return proto.CompactTextString(m) }
func (*BaseOperation) ProtoMessage()    {}
func (*BaseOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}

func (m *BaseOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseOperation.Unmarshal(m, b)
}
func (m *BaseOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseOperation.Marshal(b, m, deterministic)
}
func (m *BaseOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseOperation.Merge(m, src)
}
func (m *BaseOperation) XXX_Size() int {
	return xxx_messageInfo_BaseOperation.Size(m)
}
func (m *BaseOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseOperation.DiscardUnknown(m)
}

var xxx_messageInfo_BaseOperation proto.InternalMessageInfo

func (m *BaseOperation) GetId() *OperationID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *BaseOperation) GetOpType() TypeOfOperation {
	if m != nil {
		return m.OpType
	}
	return TypeOfOperation_Create
}

type CreateOperation struct {
	Base                 *BaseOperation `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateOperation) Reset()         { *m = CreateOperation{} }
func (m *CreateOperation) String() string { return proto.CompactTextString(m) }
func (*CreateOperation) ProtoMessage()    {}
func (*CreateOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{3}
}

func (m *CreateOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOperation.Unmarshal(m, b)
}
func (m *CreateOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOperation.Marshal(b, m, deterministic)
}
func (m *CreateOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOperation.Merge(m, src)
}
func (m *CreateOperation) XXX_Size() int {
	return xxx_messageInfo_CreateOperation.Size(m)
}
func (m *CreateOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOperation.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOperation proto.InternalMessageInfo

func (m *CreateOperation) GetBase() *BaseOperation {
	if m != nil {
		return m.Base
	}
	return nil
}

type IncreaseOperation struct {
	Base                 *BaseOperation `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Delta                int32          `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *IncreaseOperation) Reset()         { *m = IncreaseOperation{} }
func (m *IncreaseOperation) String() string { return proto.CompactTextString(m) }
func (*IncreaseOperation) ProtoMessage()    {}
func (*IncreaseOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{4}
}

func (m *IncreaseOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncreaseOperation.Unmarshal(m, b)
}
func (m *IncreaseOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncreaseOperation.Marshal(b, m, deterministic)
}
func (m *IncreaseOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncreaseOperation.Merge(m, src)
}
func (m *IncreaseOperation) XXX_Size() int {
	return xxx_messageInfo_IncreaseOperation.Size(m)
}
func (m *IncreaseOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_IncreaseOperation.DiscardUnknown(m)
}

var xxx_messageInfo_IncreaseOperation proto.InternalMessageInfo

func (m *IncreaseOperation) GetBase() *BaseOperation {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *IncreaseOperation) GetDelta() int32 {
	if m != nil {
		return m.Delta
	}
	return 0
}

type TransactionOperation struct {
	Base                 *BaseOperation `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Uuid                 []byte         `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Tag                  string         `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	NumOfOps             uint32         `protobuf:"varint,4,opt,name=numOfOps,proto3" json:"numOfOps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TransactionOperation) Reset()         { *m = TransactionOperation{} }
func (m *TransactionOperation) String() string { return proto.CompactTextString(m) }
func (*TransactionOperation) ProtoMessage()    {}
func (*TransactionOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{5}
}

func (m *TransactionOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionOperation.Unmarshal(m, b)
}
func (m *TransactionOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionOperation.Marshal(b, m, deterministic)
}
func (m *TransactionOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionOperation.Merge(m, src)
}
func (m *TransactionOperation) XXX_Size() int {
	return xxx_messageInfo_TransactionOperation.Size(m)
}
func (m *TransactionOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionOperation.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionOperation proto.InternalMessageInfo

func (m *TransactionOperation) GetBase() *BaseOperation {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *TransactionOperation) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *TransactionOperation) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *TransactionOperation) GetNumOfOps() uint32 {
	if m != nil {
		return m.NumOfOps
	}
	return 0
}

type OperationOnWire struct {
	// Types that are valid to be assigned to Body:
	//	*OperationOnWire_TransactionOperation
	//	*OperationOnWire_IncreaseOperation
	Body                 isOperationOnWire_Body `protobuf_oneof:"body"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *OperationOnWire) Reset()         { *m = OperationOnWire{} }
func (m *OperationOnWire) String() string { return proto.CompactTextString(m) }
func (*OperationOnWire) ProtoMessage()    {}
func (*OperationOnWire) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{6}
}

func (m *OperationOnWire) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperationOnWire.Unmarshal(m, b)
}
func (m *OperationOnWire) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperationOnWire.Marshal(b, m, deterministic)
}
func (m *OperationOnWire) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperationOnWire.Merge(m, src)
}
func (m *OperationOnWire) XXX_Size() int {
	return xxx_messageInfo_OperationOnWire.Size(m)
}
func (m *OperationOnWire) XXX_DiscardUnknown() {
	xxx_messageInfo_OperationOnWire.DiscardUnknown(m)
}

var xxx_messageInfo_OperationOnWire proto.InternalMessageInfo

type isOperationOnWire_Body interface {
	isOperationOnWire_Body()
}

type OperationOnWire_TransactionOperation struct {
	TransactionOperation *TransactionOperation `protobuf:"bytes,5,opt,name=transactionOperation,proto3,oneof"`
}

type OperationOnWire_IncreaseOperation struct {
	IncreaseOperation *IncreaseOperation `protobuf:"bytes,11,opt,name=increaseOperation,proto3,oneof"`
}

func (*OperationOnWire_TransactionOperation) isOperationOnWire_Body() {}

func (*OperationOnWire_IncreaseOperation) isOperationOnWire_Body() {}

func (m *OperationOnWire) GetBody() isOperationOnWire_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *OperationOnWire) GetTransactionOperation() *TransactionOperation {
	if x, ok := m.GetBody().(*OperationOnWire_TransactionOperation); ok {
		return x.TransactionOperation
	}
	return nil
}

func (m *OperationOnWire) GetIncreaseOperation() *IncreaseOperation {
	if x, ok := m.GetBody().(*OperationOnWire_IncreaseOperation); ok {
		return x.IncreaseOperation
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*OperationOnWire) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*OperationOnWire_TransactionOperation)(nil),
		(*OperationOnWire_IncreaseOperation)(nil),
	}
}

type PushPullPack struct {
	CheckPoint           *CheckPoint        `protobuf:"bytes,1,opt,name=checkPoint,proto3" json:"checkPoint,omitempty"`
	Duid                 []byte             `protobuf:"bytes,2,opt,name=duid,proto3" json:"duid,omitempty"`
	Era                  uint32             `protobuf:"varint,3,opt,name=era,proto3" json:"era,omitempty"`
	Type                 uint32             `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Operations           []*OperationOnWire `protobuf:"bytes,5,rep,name=operations,proto3" json:"operations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PushPullPack) Reset()         { *m = PushPullPack{} }
func (m *PushPullPack) String() string { return proto.CompactTextString(m) }
func (*PushPullPack) ProtoMessage()    {}
func (*PushPullPack) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{7}
}

func (m *PushPullPack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushPullPack.Unmarshal(m, b)
}
func (m *PushPullPack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushPullPack.Marshal(b, m, deterministic)
}
func (m *PushPullPack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushPullPack.Merge(m, src)
}
func (m *PushPullPack) XXX_Size() int {
	return xxx_messageInfo_PushPullPack.Size(m)
}
func (m *PushPullPack) XXX_DiscardUnknown() {
	xxx_messageInfo_PushPullPack.DiscardUnknown(m)
}

var xxx_messageInfo_PushPullPack proto.InternalMessageInfo

func (m *PushPullPack) GetCheckPoint() *CheckPoint {
	if m != nil {
		return m.CheckPoint
	}
	return nil
}

func (m *PushPullPack) GetDuid() []byte {
	if m != nil {
		return m.Duid
	}
	return nil
}

func (m *PushPullPack) GetEra() uint32 {
	if m != nil {
		return m.Era
	}
	return 0
}

func (m *PushPullPack) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *PushPullPack) GetOperations() []*OperationOnWire {
	if m != nil {
		return m.Operations
	}
	return nil
}

type CheckPoint struct {
	Sseq                 uint64   `protobuf:"varint,1,opt,name=sseq,proto3" json:"sseq,omitempty"`
	Cseq                 uint64   `protobuf:"varint,2,opt,name=cseq,proto3" json:"cseq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPoint) Reset()         { *m = CheckPoint{} }
func (m *CheckPoint) String() string { return proto.CompactTextString(m) }
func (*CheckPoint) ProtoMessage()    {}
func (*CheckPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{8}
}

func (m *CheckPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPoint.Unmarshal(m, b)
}
func (m *CheckPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPoint.Marshal(b, m, deterministic)
}
func (m *CheckPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPoint.Merge(m, src)
}
func (m *CheckPoint) XXX_Size() int {
	return xxx_messageInfo_CheckPoint.Size(m)
}
func (m *CheckPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPoint.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPoint proto.InternalMessageInfo

func (m *CheckPoint) GetSseq() uint64 {
	if m != nil {
		return m.Sseq
	}
	return 0
}

func (m *CheckPoint) GetCseq() uint64 {
	if m != nil {
		return m.Cseq
	}
	return 0
}

func init() {
	proto.RegisterEnum("model.TypeOfSync", TypeOfSync_name, TypeOfSync_value)
	proto.RegisterEnum("model.TypeOfOperation", TypeOfOperation_name, TypeOfOperation_value)
	proto.RegisterEnum("model.TypeOfDatatype", TypeOfDatatype_name, TypeOfDatatype_value)
	proto.RegisterEnum("model.StateOfDatatype", StateOfDatatype_name, StateOfDatatype_value)
	proto.RegisterType((*Client)(nil), "model.Client")
	proto.RegisterType((*OperationID)(nil), "model.OperationID")
	proto.RegisterType((*BaseOperation)(nil), "model.BaseOperation")
	proto.RegisterType((*CreateOperation)(nil), "model.CreateOperation")
	proto.RegisterType((*IncreaseOperation)(nil), "model.IncreaseOperation")
	proto.RegisterType((*TransactionOperation)(nil), "model.TransactionOperation")
	proto.RegisterType((*OperationOnWire)(nil), "model.OperationOnWire")
	proto.RegisterType((*PushPullPack)(nil), "model.PushPullPack")
	proto.RegisterType((*CheckPoint)(nil), "model.CheckPoint")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 696 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x41, 0x6f, 0xda, 0x4c,
	0x10, 0x65, 0xc1, 0xf0, 0x91, 0x01, 0xc2, 0xb2, 0xe1, 0xab, 0xac, 0x56, 0xaa, 0x90, 0x4f, 0x88,
	0xb6, 0x91, 0x9a, 0x56, 0xbd, 0xf4, 0x44, 0x8c, 0x15, 0x5c, 0xd1, 0x35, 0x5d, 0x3b, 0x4a, 0x73,
	0x42, 0x1b, 0xb3, 0x6d, 0xac, 0x38, 0x36, 0xb5, 0xcd, 0x81, 0x63, 0x7b, 0xea, 0xff, 0xa9, 0xd4,
	0xdf, 0x57, 0xed, 0x62, 0x1c, 0x93, 0xe4, 0x50, 0xf5, 0x36, 0x33, 0x7e, 0x33, 0xf3, 0xe6, 0xed,
	0x8c, 0xa1, 0x75, 0x1b, 0x2f, 0x45, 0x78, 0xbc, 0x4a, 0xe2, 0x2c, 0x26, 0x75, 0xe5, 0x18, 0xdf,
	0x11, 0x34, 0xcc, 0x30, 0x10, 0x51, 0x46, 0x08, 0x68, 0xfe, 0x3a, 0x58, 0xea, 0x68, 0x80, 0x86,
	0x6d, 0xa6, 0x6c, 0xd2, 0x87, 0x3a, 0x0f, 0x03, 0x9e, 0xea, 0xd5, 0x01, 0x1a, 0x1e, 0xb0, 0xad,
	0x43, 0x9e, 0x03, 0xf8, 0x71, 0x18, 0x0a, 0x3f, 0x0b, 0xe2, 0x48, 0xaf, 0xa9, 0x4f, 0xa5, 0x08,
	0x79, 0x05, 0xcd, 0x74, 0x13, 0xf9, 0xde, 0x66, 0x25, 0x74, 0x6d, 0x80, 0x86, 0x87, 0x27, 0xbd,
	0xe3, 0x6d, 0x6f, 0x19, 0x72, 0xbe, 0xb8, 0x9b, 0xc8, 0x67, 0x05, 0xc4, 0x58, 0x40, 0xcb, 0x59,
	0x89, 0x84, 0xcb, 0x5c, 0x7b, 0x42, 0x30, 0xd4, 0x44, 0xc2, 0x15, 0x8d, 0x0e, 0x93, 0x26, 0xd1,
	0xe1, 0xbf, 0x90, 0xdf, 0xae, 0xe2, 0x24, 0x53, 0x3c, 0x34, 0xb6, 0x73, 0x0b, 0xce, 0xb5, 0x12,
	0x67, 0x0c, 0xb5, 0x54, 0x7c, 0x53, 0x8d, 0x35, 0x26, 0x4d, 0xc3, 0x87, 0xce, 0x29, 0x4f, 0x45,
	0xd1, 0x84, 0x18, 0x50, 0xcd, 0x07, 0x6d, 0x9d, 0x90, 0x9c, 0x5a, 0x89, 0x02, 0xab, 0x06, 0x4b,
	0x72, 0x0c, 0x8d, 0x78, 0xa5, 0x46, 0xa8, 0xaa, 0x11, 0x9e, 0xec, 0x8d, 0x50, 0xa0, 0x59, 0x8e,
	0x32, 0xde, 0x43, 0xd7, 0x4c, 0x04, 0xcf, 0x4a, 0x6d, 0x86, 0xa0, 0x5d, 0xf1, 0x54, 0xe4, 0x8d,
	0xfa, 0x79, 0x81, 0x3d, 0x2a, 0x4c, 0x21, 0x0c, 0x17, 0x7a, 0x76, 0xe4, 0x27, 0x62, 0x8f, 0xe5,
	0x5f, 0xa7, 0xcb, 0x67, 0x5a, 0x8a, 0x30, 0xe3, 0x8a, 0x6a, 0x9d, 0x6d, 0x1d, 0xe3, 0x07, 0x82,
	0xbe, 0x97, 0xf0, 0x28, 0xe5, 0xea, 0x59, 0xfe, 0xa5, 0x30, 0x01, 0x6d, 0x2d, 0xf5, 0xad, 0x6e,
	0xf5, 0x5d, 0xe7, 0xfa, 0x66, 0xfc, 0x6b, 0xfe, 0xec, 0xd2, 0x24, 0x4f, 0xa1, 0x19, 0xad, 0x6f,
	0xa5, 0x28, 0xa9, 0x92, 0xbd, 0xc3, 0x0a, 0xdf, 0xf8, 0x8d, 0xa0, 0x5b, 0x54, 0x75, 0xa2, 0x8b,
	0x20, 0x11, 0xe4, 0x13, 0xf4, 0xb3, 0x47, 0x78, 0xe9, 0x75, 0xc5, 0xe7, 0xd9, 0x4e, 0xe8, 0x47,
	0x20, 0xd3, 0x0a, 0x7b, 0x34, 0x95, 0x4c, 0xa1, 0x17, 0xdc, 0x17, 0x50, 0x6f, 0xa9, 0x7a, 0x7a,
	0x5e, 0xef, 0x81, 0xc0, 0xd3, 0x0a, 0x7b, 0x98, 0x74, 0xda, 0x00, 0xed, 0x2a, 0x5e, 0x6e, 0x8c,
	0x5f, 0x08, 0xda, 0xf3, 0x75, 0x7a, 0x3d, 0x5f, 0x87, 0xe1, 0x9c, 0xfb, 0x37, 0xe4, 0x35, 0x80,
	0x7f, 0x2d, 0xfc, 0x9b, 0x79, 0x1c, 0x44, 0x59, 0xae, 0xdd, 0x6e, 0xaf, 0xcd, 0xe2, 0x03, 0x2b,
	0x81, 0xa4, 0x7c, 0xcb, 0x92, 0x7c, 0xcb, 0x5c, 0x3e, 0xb9, 0xde, 0xb5, 0xbb, 0xf5, 0x26, 0xa0,
	0x65, 0xbb, 0x53, 0xe9, 0x30, 0x65, 0x93, 0x77, 0x00, 0xf1, 0x8e, 0x52, 0xaa, 0xd7, 0x07, 0xb5,
	0x61, 0xab, 0xd8, 0xc0, 0x7b, 0x72, 0xb2, 0x12, 0xd2, 0x78, 0x0b, 0x60, 0xee, 0xf5, 0x4f, 0xe5,
	0x2d, 0x20, 0x75, 0x0b, 0xca, 0x56, 0x27, 0x23, 0x63, 0xdb, 0x4b, 0x52, 0xf6, 0xe8, 0x25, 0xc0,
	0xdd, 0x65, 0x92, 0x36, 0x34, 0x3f, 0x8e, 0xe9, 0xf9, 0x78, 0x36, 0xbb, 0xc4, 0x15, 0x82, 0xa1,
	0x6d, 0x53, 0xd7, 0x1b, 0x53, 0x6f, 0x76, 0xb9, 0xb8, 0x70, 0x31, 0x1a, 0xfd, 0x44, 0xd0, 0xbd,
	0x77, 0x05, 0x04, 0xa0, 0xb1, 0xdd, 0x7e, 0x5c, 0x91, 0xf6, 0xc4, 0x9a, 0x59, 0x9e, 0x85, 0x11,
	0x39, 0x80, 0xba, 0xc5, 0x98, 0xc3, 0x70, 0x55, 0x96, 0x75, 0xe9, 0x78, 0xee, 0x4e, 0x1d, 0x0f,
	0x6b, 0xe4, 0x7f, 0xe8, 0x79, 0x6c, 0x4c, 0xdd, 0xb1, 0xe9, 0xd9, 0x0e, 0x5d, 0x9c, 0x5a, 0x67,
	0x36, 0xc5, 0x75, 0x72, 0x04, 0xdd, 0x72, 0xd8, 0xa2, 0x13, 0xdc, 0x20, 0x3a, 0xf4, 0x6d, 0xea,
	0x2d, 0x4c, 0xe7, 0x9c, 0x7a, 0x16, 0x5b, 0xd8, 0xd4, 0x64, 0xd6, 0xd8, 0xb5, 0x70, 0x6b, 0xf4,
	0x02, 0x0e, 0xb7, 0x4c, 0x26, 0x3c, 0xe3, 0x4a, 0xb8, 0x2e, 0xb4, 0x4a, 0x58, 0x5c, 0x21, 0x4d,
	0xd0, 0x3e, 0xb8, 0x0e, 0xc5, 0x68, 0x74, 0x09, 0x5d, 0x37, 0x93, 0x07, 0x7a, 0x87, 0x3e, 0x82,
	0xee, 0xcc, 0x31, 0xe5, 0xa4, 0x0b, 0xeb, 0xb3, 0xed, 0x7a, 0xd6, 0x04, 0x57, 0x64, 0x09, 0x66,
	0x9d, 0x49, 0x8f, 0xd9, 0xf4, 0x0c, 0x23, 0x72, 0x08, 0xb0, 0x0b, 0x58, 0x13, 0x5c, 0x95, 0x92,
	0x9c, 0xd3, 0x52, 0xa4, 0x76, 0xd5, 0x50, 0x3f, 0xd5, 0x37, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x74, 0x3b, 0x64, 0x64, 0x63, 0x05, 0x00, 0x00,
}
