// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request_reply.proto

package model

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TypeOfRequest int32

const (
	TypeOfRequest_PUSHPULL_REQUEST TypeOfRequest = 0
	TypeOfRequest_CLIENT_REQUEST   TypeOfRequest = 1
)

var TypeOfRequest_name = map[int32]string{
	0: "PUSHPULL_REQUEST",
	1: "CLIENT_REQUEST",
}

var TypeOfRequest_value = map[string]int32{
	"PUSHPULL_REQUEST": 0,
	"CLIENT_REQUEST":   1,
}

func (x TypeOfRequest) String() string {
	return proto.EnumName(TypeOfRequest_name, int32(x))
}

func (TypeOfRequest) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7bf67568605725bb, []int{0}
}

type TypeOfResponse int32

const (
	TypeOfResponse_PUSHPULL_REPLY TypeOfResponse = 0
	TypeOfResponse_CLIENT_REPLY   TypeOfResponse = 1
)

var TypeOfResponse_name = map[int32]string{
	0: "PUSHPULL_REPLY",
	1: "CLIENT_REPLY",
}

var TypeOfResponse_value = map[string]int32{
	"PUSHPULL_REPLY": 0,
	"CLIENT_REPLY":   1,
}

func (x TypeOfResponse) String() string {
	return proto.EnumName(TypeOfResponse_name, int32(x))
}

func (TypeOfResponse) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7bf67568605725bb, []int{1}
}

type StateOfResponse int32

const (
	StateOfResponse_OK                            StateOfResponse = 0
	StateOfResponse_ERR_CLIENT_INVALID_COLLECTION StateOfResponse = 101
	StateOfResponse_ERR_CLIENT_INVALID_SYNCTYPE   StateOfResponse = 102
)

var StateOfResponse_name = map[int32]string{
	0:   "OK",
	101: "ERR_CLIENT_INVALID_COLLECTION",
	102: "ERR_CLIENT_INVALID_SYNCTYPE",
}

var StateOfResponse_value = map[string]int32{
	"OK":                            0,
	"ERR_CLIENT_INVALID_COLLECTION": 101,
	"ERR_CLIENT_INVALID_SYNCTYPE":   102,
}

func (x StateOfResponse) String() string {
	return proto.EnumName(StateOfResponse_name, int32(x))
}

func (StateOfResponse) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7bf67568605725bb, []int{2}
}

type RequestHeader struct {
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Seq     uint32 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	// Types that are valid to be assigned to TypeOf:
	//	*RequestHeader_TypeOfRequest
	//	*RequestHeader_TypeOfReply
	TypeOf               isRequestHeader_TypeOf `protobuf_oneof:"typeOf"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf67568605725bb, []int{0}
}

func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeader.Unmarshal(m, b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
}
func (m *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(m, src)
}
func (m *RequestHeader) XXX_Size() int {
	return xxx_messageInfo_RequestHeader.Size(m)
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *RequestHeader) GetSeq() uint32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type isRequestHeader_TypeOf interface {
	isRequestHeader_TypeOf()
}

type RequestHeader_TypeOfRequest struct {
	TypeOfRequest TypeOfRequest `protobuf:"varint,3,opt,name=typeOfRequest,proto3,enum=model.TypeOfRequest,oneof"`
}

type RequestHeader_TypeOfReply struct {
	TypeOfReply TypeOfResponse `protobuf:"varint,4,opt,name=typeOfReply,proto3,enum=model.TypeOfResponse,oneof"`
}

func (*RequestHeader_TypeOfRequest) isRequestHeader_TypeOf() {}

func (*RequestHeader_TypeOfReply) isRequestHeader_TypeOf() {}

func (m *RequestHeader) GetTypeOf() isRequestHeader_TypeOf {
	if m != nil {
		return m.TypeOf
	}
	return nil
}

func (m *RequestHeader) GetTypeOfRequest() TypeOfRequest {
	if x, ok := m.GetTypeOf().(*RequestHeader_TypeOfRequest); ok {
		return x.TypeOfRequest
	}
	return TypeOfRequest_PUSHPULL_REQUEST
}

func (m *RequestHeader) GetTypeOfReply() TypeOfResponse {
	if x, ok := m.GetTypeOf().(*RequestHeader_TypeOfReply); ok {
		return x.TypeOfReply
	}
	return TypeOfResponse_PUSHPULL_REPLY
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RequestHeader) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RequestHeader_TypeOfRequest)(nil),
		(*RequestHeader_TypeOfReply)(nil),
	}
}

type ResponseHeader struct {
	Type                 TypeOfResponse `protobuf:"varint,1,opt,name=type,proto3,enum=model.TypeOfResponse" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ResponseHeader) Reset()         { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()    {}
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf67568605725bb, []int{1}
}

func (m *ResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseHeader.Unmarshal(m, b)
}
func (m *ResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseHeader.Marshal(b, m, deterministic)
}
func (m *ResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHeader.Merge(m, src)
}
func (m *ResponseHeader) XXX_Size() int {
	return xxx_messageInfo_ResponseHeader.Size(m)
}
func (m *ResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHeader proto.InternalMessageInfo

func (m *ResponseHeader) GetType() TypeOfResponse {
	if m != nil {
		return m.Type
	}
	return TypeOfResponse_PUSHPULL_REPLY
}

type ClientRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Client               *Client        `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ClientRequest) Reset()         { *m = ClientRequest{} }
func (m *ClientRequest) String() string { return proto.CompactTextString(m) }
func (*ClientRequest) ProtoMessage()    {}
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf67568605725bb, []int{2}
}

func (m *ClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientRequest.Unmarshal(m, b)
}
func (m *ClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientRequest.Marshal(b, m, deterministic)
}
func (m *ClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientRequest.Merge(m, src)
}
func (m *ClientRequest) XXX_Size() int {
	return xxx_messageInfo_ClientRequest.Size(m)
}
func (m *ClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientRequest proto.InternalMessageInfo

func (m *ClientRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ClientRequest) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

type ResponseState struct {
	State                StateOfResponse `protobuf:"varint,1,opt,name=state,proto3,enum=model.StateOfResponse" json:"state,omitempty"`
	Msg                  string          `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ResponseState) Reset()         { *m = ResponseState{} }
func (m *ResponseState) String() string { return proto.CompactTextString(m) }
func (*ResponseState) ProtoMessage()    {}
func (*ResponseState) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf67568605725bb, []int{3}
}

func (m *ResponseState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseState.Unmarshal(m, b)
}
func (m *ResponseState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseState.Marshal(b, m, deterministic)
}
func (m *ResponseState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseState.Merge(m, src)
}
func (m *ResponseState) XXX_Size() int {
	return xxx_messageInfo_ResponseState.Size(m)
}
func (m *ResponseState) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseState.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseState proto.InternalMessageInfo

func (m *ResponseState) GetState() StateOfResponse {
	if m != nil {
		return m.State
	}
	return StateOfResponse_OK
}

func (m *ResponseState) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ClientResponse struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	State                *ResponseState `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ClientResponse) Reset()         { *m = ClientResponse{} }
func (m *ClientResponse) String() string { return proto.CompactTextString(m) }
func (*ClientResponse) ProtoMessage()    {}
func (*ClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf67568605725bb, []int{4}
}

func (m *ClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientResponse.Unmarshal(m, b)
}
func (m *ClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientResponse.Marshal(b, m, deterministic)
}
func (m *ClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientResponse.Merge(m, src)
}
func (m *ClientResponse) XXX_Size() int {
	return xxx_messageInfo_ClientResponse.Size(m)
}
func (m *ClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClientResponse proto.InternalMessageInfo

func (m *ClientResponse) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ClientResponse) GetState() *ResponseState {
	if m != nil {
		return m.State
	}
	return nil
}

type PushPullRequest struct {
	Header               *RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   int32           `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	PushPullPacks        []*PushPullPack `protobuf:"bytes,3,rep,name=pushPullPacks,proto3" json:"pushPullPacks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PushPullRequest) Reset()         { *m = PushPullRequest{} }
func (m *PushPullRequest) String() string { return proto.CompactTextString(m) }
func (*PushPullRequest) ProtoMessage()    {}
func (*PushPullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf67568605725bb, []int{5}
}

func (m *PushPullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushPullRequest.Unmarshal(m, b)
}
func (m *PushPullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushPullRequest.Marshal(b, m, deterministic)
}
func (m *PushPullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushPullRequest.Merge(m, src)
}
func (m *PushPullRequest) XXX_Size() int {
	return xxx_messageInfo_PushPullRequest.Size(m)
}
func (m *PushPullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushPullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushPullRequest proto.InternalMessageInfo

func (m *PushPullRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PushPullRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PushPullRequest) GetPushPullPacks() []*PushPullPack {
	if m != nil {
		return m.PushPullPacks
	}
	return nil
}

type PushPullResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   int32           `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	PushPullPacks        []*PushPullPack `protobuf:"bytes,3,rep,name=pushPullPacks,proto3" json:"pushPullPacks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PushPullResponse) Reset()         { *m = PushPullResponse{} }
func (m *PushPullResponse) String() string { return proto.CompactTextString(m) }
func (*PushPullResponse) ProtoMessage()    {}
func (*PushPullResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf67568605725bb, []int{6}
}

func (m *PushPullResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushPullResponse.Unmarshal(m, b)
}
func (m *PushPullResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushPullResponse.Marshal(b, m, deterministic)
}
func (m *PushPullResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushPullResponse.Merge(m, src)
}
func (m *PushPullResponse) XXX_Size() int {
	return xxx_messageInfo_PushPullResponse.Size(m)
}
func (m *PushPullResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PushPullResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PushPullResponse proto.InternalMessageInfo

func (m *PushPullResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PushPullResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PushPullResponse) GetPushPullPacks() []*PushPullPack {
	if m != nil {
		return m.PushPullPacks
	}
	return nil
}

func init() {
	proto.RegisterEnum("model.TypeOfRequest", TypeOfRequest_name, TypeOfRequest_value)
	proto.RegisterEnum("model.TypeOfResponse", TypeOfResponse_name, TypeOfResponse_value)
	proto.RegisterEnum("model.StateOfResponse", StateOfResponse_name, StateOfResponse_value)
	proto.RegisterType((*RequestHeader)(nil), "model.RequestHeader")
	proto.RegisterType((*ResponseHeader)(nil), "model.ResponseHeader")
	proto.RegisterType((*ClientRequest)(nil), "model.ClientRequest")
	proto.RegisterType((*ResponseState)(nil), "model.ResponseState")
	proto.RegisterType((*ClientResponse)(nil), "model.ClientResponse")
	proto.RegisterType((*PushPullRequest)(nil), "model.PushPullRequest")
	proto.RegisterType((*PushPullResponse)(nil), "model.PushPullResponse")
}

func init() { proto.RegisterFile("request_reply.proto", fileDescriptor_7bf67568605725bb) }

var fileDescriptor_7bf67568605725bb = []byte{
	// 543 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x51, 0x8f, 0xd2, 0x4c,
	0x14, 0x65, 0x60, 0xe1, 0xfb, 0xf6, 0xb2, 0x2d, 0xcd, 0x2c, 0xac, 0xcd, 0x1a, 0x23, 0x36, 0x31,
	0x41, 0xb2, 0xee, 0x03, 0x26, 0x26, 0xc4, 0x7d, 0x71, 0xb1, 0x09, 0xc4, 0x86, 0xd6, 0xa1, 0x98,
	0xf0, 0x60, 0x08, 0xd2, 0x59, 0xb7, 0xda, 0xa5, 0xdd, 0x4e, 0xd9, 0x84, 0xbf, 0x60, 0x7c, 0xf0,
	0x17, 0xf9, 0xdb, 0x4c, 0x67, 0xa6, 0xd8, 0x56, 0x7d, 0xd0, 0xc4, 0x27, 0x66, 0xee, 0x3d, 0xe7,
	0xdc, 0x73, 0x4f, 0x86, 0xc2, 0x71, 0x4c, 0x6f, 0xb7, 0x94, 0x25, 0xcb, 0x98, 0x46, 0xc1, 0xee,
	0x3c, 0x8a, 0xc3, 0x24, 0xc4, 0xf5, 0x9b, 0xd0, 0xa3, 0xc1, 0x69, 0x93, 0xff, 0x88, 0x9a, 0xf1,
	0x0d, 0x81, 0x42, 0x04, 0x76, 0x4c, 0x57, 0x1e, 0x8d, 0xb1, 0x0e, 0xff, 0xdd, 0xd1, 0x98, 0xf9,
	0xe1, 0x46, 0x47, 0x5d, 0xd4, 0x3b, 0x24, 0xd9, 0x15, 0x6b, 0x50, 0x63, 0xf4, 0x56, 0xaf, 0x76,
	0x51, 0x4f, 0x21, 0xe9, 0x11, 0x5f, 0x80, 0x92, 0xec, 0x22, 0x6a, 0x5f, 0x49, 0x09, 0xbd, 0xd6,
	0x45, 0x3d, 0x75, 0xd0, 0x3e, 0x17, 0x23, 0xdc, 0x7c, 0x6f, 0x5c, 0x21, 0x45, 0x30, 0x1e, 0x42,
	0x33, 0x2b, 0x44, 0xc1, 0x4e, 0x3f, 0xe0, 0xdc, 0x4e, 0x89, 0xcb, 0xa2, 0x70, 0xc3, 0xe8, 0xb8,
	0x42, 0xf2, 0xd8, 0xcb, 0xff, 0xa1, 0x21, 0xae, 0xc6, 0x0b, 0x50, 0xf7, 0x20, 0xb1, 0xc0, 0x13,
	0x38, 0x48, 0x7b, 0xdc, 0xfd, 0xef, 0xf4, 0x08, 0x87, 0x18, 0x1e, 0x28, 0xa3, 0xc0, 0xa7, 0x9b,
	0x24, 0xb3, 0x74, 0x06, 0x8d, 0x6b, 0xae, 0xc2, 0xd9, 0xcd, 0xfd, 0x26, 0x85, 0x88, 0x88, 0xc4,
	0xe0, 0xc7, 0xd0, 0x58, 0x73, 0x3a, 0xcf, 0xa4, 0x39, 0x50, 0x24, 0x5a, 0x6a, 0xca, 0xa6, 0x61,
	0xa7, 0x11, 0x8b, 0xb9, 0xb3, 0x64, 0x95, 0x50, 0x7c, 0x06, 0x75, 0x96, 0x1e, 0xa4, 0xc5, 0x13,
	0x49, 0xe3, 0xcd, 0x9c, 0x47, 0x01, 0x4a, 0x63, 0xbf, 0x61, 0x1f, 0xf8, 0x88, 0x43, 0x92, 0x1e,
	0x8d, 0x8f, 0xa0, 0x66, 0xb6, 0x05, 0xf4, 0x0f, 0x7d, 0xf7, 0xb3, 0xf9, 0xd5, 0x12, 0x38, 0x67,
	0x52, 0x4e, 0x37, 0x3e, 0x23, 0x68, 0x39, 0x5b, 0x76, 0xed, 0x6c, 0x83, 0xe0, 0xef, 0x52, 0x52,
	0xa1, 0xea, 0x7b, 0x7c, 0x54, 0x9d, 0x54, 0x7d, 0x0f, 0x0f, 0x41, 0x89, 0xa4, 0xa0, 0xb3, 0x5a,
	0x7f, 0x62, 0x7a, 0xad, 0x5b, 0xeb, 0x35, 0x07, 0xc7, 0x52, 0xc4, 0xc9, 0xf5, 0x48, 0x11, 0x69,
	0x7c, 0x41, 0xa0, 0xfd, 0x30, 0x23, 0x77, 0x7f, 0x5a, 0x72, 0xd3, 0x29, 0xad, 0xf3, 0xcf, 0xec,
	0xf4, 0x87, 0xa0, 0x14, 0x9e, 0x38, 0x6e, 0x83, 0xe6, 0xcc, 0x67, 0x63, 0x67, 0x6e, 0x59, 0x4b,
	0x62, 0xbe, 0x99, 0x9b, 0x33, 0x57, 0xab, 0x60, 0x0c, 0xea, 0xc8, 0x9a, 0x98, 0x53, 0x77, 0x5f,
	0x43, 0xfd, 0xe7, 0xa0, 0x16, 0x5f, 0x64, 0x8a, 0xca, 0x71, 0x1d, 0x6b, 0xa1, 0x55, 0xb0, 0x06,
	0x47, 0x7b, 0x66, 0x5a, 0x41, 0xfd, 0x77, 0xd0, 0x2a, 0x3d, 0x13, 0xdc, 0x80, 0xaa, 0xfd, 0x5a,
	0xab, 0xe0, 0x47, 0xf0, 0xc0, 0x24, 0x64, 0x29, 0x09, 0x93, 0xe9, 0xdb, 0x97, 0xd6, 0xe4, 0xd5,
	0x72, 0x64, 0x5b, 0x96, 0x39, 0x72, 0x27, 0xf6, 0x54, 0xa3, 0xf8, 0x21, 0xdc, 0xff, 0x05, 0x64,
	0xb6, 0x98, 0x8e, 0xdc, 0x85, 0x63, 0x6a, 0x57, 0x83, 0xaf, 0x08, 0x8e, 0xec, 0x38, 0x09, 0xc3,
	0x19, 0x8d, 0xef, 0xfc, 0x35, 0xc5, 0x97, 0xd0, 0x72, 0xe2, 0x70, 0x4d, 0x19, 0xcb, 0x82, 0xc0,
	0x27, 0xa5, 0x64, 0xe4, 0xf2, 0xa7, 0xf7, 0x7e, 0xaa, 0x4b, 0x83, 0x17, 0xa0, 0x48, 0x0d, 0xf1,
	0x6a, 0x71, 0xbb, 0xf8, 0x3f, 0x91, 0xfc, 0x4e, 0xa9, 0x2a, 0xd8, 0xef, 0x1b, 0xfc, 0x43, 0xf5,
	0xec, 0x7b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x62, 0x67, 0x3c, 0x5f, 0xd3, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrtooServiceClient is the client API for OrtooService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrtooServiceClient interface {
	ProcessPushPull(ctx context.Context, in *PushPullRequest, opts ...grpc.CallOption) (*PushPullResponse, error)
	ProcessClient(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ClientResponse, error)
}

type ortooServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrtooServiceClient(cc *grpc.ClientConn) OrtooServiceClient {
	return &ortooServiceClient{cc}
}

func (c *ortooServiceClient) ProcessPushPull(ctx context.Context, in *PushPullRequest, opts ...grpc.CallOption) (*PushPullResponse, error) {
	out := new(PushPullResponse)
	err := c.cc.Invoke(ctx, "/model.OrtooService/ProcessPushPull", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ortooServiceClient) ProcessClient(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ClientResponse, error) {
	out := new(ClientResponse)
	err := c.cc.Invoke(ctx, "/model.OrtooService/ProcessClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrtooServiceServer is the server API for OrtooService service.
type OrtooServiceServer interface {
	ProcessPushPull(context.Context, *PushPullRequest) (*PushPullResponse, error)
	ProcessClient(context.Context, *ClientRequest) (*ClientResponse, error)
}

func RegisterOrtooServiceServer(s *grpc.Server, srv OrtooServiceServer) {
	s.RegisterService(&_OrtooService_serviceDesc, srv)
}

func _OrtooService_ProcessPushPull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushPullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrtooServiceServer).ProcessPushPull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.OrtooService/ProcessPushPull",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrtooServiceServer).ProcessPushPull(ctx, req.(*PushPullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrtooService_ProcessClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrtooServiceServer).ProcessClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.OrtooService/ProcessClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrtooServiceServer).ProcessClient(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrtooService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.OrtooService",
	HandlerType: (*OrtooServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessPushPull",
			Handler:    _OrtooService_ProcessPushPull_Handler,
		},
		{
			MethodName: "ProcessClient",
			Handler:    _OrtooService_ProcessClient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "request_reply.proto",
}
