// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: orda.grpc.proto

package model

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SnapshotRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Collection           string   `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Duid                 string   `protobuf:"bytes,3,opt,name=duid,proto3" json:"duid,omitempty"`
	Sseq                 uint64   `protobuf:"varint,4,opt,name=sseq,proto3" json:"sseq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SnapshotRequest) Reset()         { *m = SnapshotRequest{} }
func (m *SnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*SnapshotRequest) ProtoMessage()    {}
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b962502dfda3ec7a, []int{0}
}
func (m *SnapshotRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SnapshotRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotRequest.Merge(m, src)
}
func (m *SnapshotRequest) XXX_Size() int {
	return m.Size()
}
func (m *SnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotRequest proto.InternalMessageInfo

func (m *SnapshotRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SnapshotRequest) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

func (m *SnapshotRequest) GetDuid() string {
	if m != nil {
		return m.Duid
	}
	return ""
}

func (m *SnapshotRequest) GetSseq() uint64 {
	if m != nil {
		return m.Sseq
	}
	return 0
}

type SnapshotResponse struct {
	Meta                 *DatatypeMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Json                 string        `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SnapshotResponse) Reset()         { *m = SnapshotResponse{} }
func (m *SnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*SnapshotResponse) ProtoMessage()    {}
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b962502dfda3ec7a, []int{1}
}
func (m *SnapshotResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SnapshotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SnapshotResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SnapshotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotResponse.Merge(m, src)
}
func (m *SnapshotResponse) XXX_Size() int {
	return m.Size()
}
func (m *SnapshotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotResponse proto.InternalMessageInfo

func (m *SnapshotResponse) GetMeta() *DatatypeMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *SnapshotResponse) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

type EncodingMessage struct {
	Type                 TypeOfDatatype `protobuf:"varint,1,opt,name=type,proto3,enum=orda.TypeOfDatatype" json:"type,omitempty"`
	Op                   *Operation     `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *EncodingMessage) Reset()         { *m = EncodingMessage{} }
func (m *EncodingMessage) String() string { return proto.CompactTextString(m) }
func (*EncodingMessage) ProtoMessage()    {}
func (*EncodingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b962502dfda3ec7a, []int{2}
}
func (m *EncodingMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EncodingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EncodingMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EncodingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncodingMessage.Merge(m, src)
}
func (m *EncodingMessage) XXX_Size() int {
	return m.Size()
}
func (m *EncodingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EncodingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EncodingMessage proto.InternalMessageInfo

func (m *EncodingMessage) GetType() TypeOfDatatype {
	if m != nil {
		return m.Type
	}
	return TypeOfDatatype_COUNTER
}

func (m *EncodingMessage) GetOp() *Operation {
	if m != nil {
		return m.Op
	}
	return nil
}

func init() {
	proto.RegisterType((*SnapshotRequest)(nil), "orda.SnapshotRequest")
	proto.RegisterType((*SnapshotResponse)(nil), "orda.SnapshotResponse")
	proto.RegisterType((*EncodingMessage)(nil), "orda.EncodingMessage")
}

func init() { proto.RegisterFile("orda.grpc.proto", fileDescriptor_b962502dfda3ec7a) }

var fileDescriptor_b962502dfda3ec7a = []byte{
	// 589 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xb1, 0x6b, 0x40, 0x6c, 0x05, 0xae, 0x16, 0x5a, 0x82, 0x55, 0x19, 0x6b, 0x85, 0xaa,
	0xa8, 0x52, 0xe3, 0xd6, 0x20, 0x84, 0x02, 0x97, 0x36, 0x70, 0xe0, 0x50, 0x1a, 0xb9, 0x3d, 0x21,
	0x2e, 0x8b, 0x3d, 0xb8, 0xa6, 0xce, 0xee, 0xd6, 0xbb, 0x0e, 0x8a, 0xaa, 0x5c, 0x78, 0x04, 0xb8,
	0xf0, 0x48, 0x1c, 0x11, 0xbc, 0x00, 0x0a, 0x3c, 0x08, 0xf2, 0xda, 0x4e, 0xaa, 0x10, 0x94, 0x03,
	0x27, 0xef, 0xfc, 0xe7, 0xe3, 0xb7, 0x33, 0x3b, 0x32, 0xb2, 0x79, 0x1e, 0xd3, 0x4e, 0x92, 0x8b,
	0xa8, 0x23, 0x72, 0xae, 0x38, 0xb6, 0x4a, 0xc1, 0x41, 0x5a, 0xd6, 0x8a, 0x53, 0x85, 0x00, 0x2b,
	0x06, 0xb5, 0xb0, 0x99, 0x70, 0x9e, 0x64, 0xe0, 0x53, 0x91, 0xfa, 0x94, 0x31, 0xae, 0xa8, 0x4a,
	0x39, 0x93, 0xb5, 0xb7, 0xfa, 0x44, 0x3b, 0x09, 0xb0, 0x1d, 0x2e, 0x80, 0x51, 0x91, 0x0e, 0x03,
	0x9f, 0x0b, 0x1d, 0xf3, 0x77, 0x3c, 0xe1, 0xc8, 0x3e, 0x66, 0x54, 0xc8, 0x53, 0xae, 0x42, 0x38,
	0x2f, 0x40, 0x2a, 0xbc, 0x86, 0x56, 0xce, 0x60, 0xd4, 0x32, 0x3c, 0xa3, 0x7d, 0x23, 0x2c, 0x8f,
	0xd8, 0x45, 0x28, 0xe2, 0x59, 0x06, 0x51, 0x99, 0xd9, 0x32, 0xb5, 0xe3, 0x92, 0x82, 0x31, 0xb2,
	0xe2, 0x22, 0x8d, 0x5b, 0x2b, 0xda, 0xa3, 0xcf, 0x78, 0x03, 0x59, 0x52, 0xc2, 0x79, 0xcb, 0xf2,
	0x8c, 0xb6, 0x75, 0x60, 0xee, 0x1a, 0xa1, 0xb6, 0xc9, 0x2b, 0xb4, 0x36, 0x03, 0x4a, 0xc1, 0x99,
	0x04, 0xbc, 0x85, 0xac, 0x01, 0x28, 0xaa, 0x91, 0xab, 0x01, 0xee, 0xe8, 0x96, 0x9f, 0x53, 0x45,
	0xd5, 0x48, 0xc0, 0x21, 0x28, 0x1a, 0x6a, 0x7f, 0xc9, 0x79, 0x2f, 0xa7, 0x37, 0xd0, 0x67, 0xf2,
	0x06, 0xd9, 0x2f, 0x58, 0xc4, 0xe3, 0x94, 0x25, 0x87, 0x20, 0x25, 0x4d, 0x00, 0xb7, 0x91, 0x55,
	0x26, 0xea, 0x72, 0xb7, 0x82, 0x3b, 0x55, 0xb9, 0x93, 0x91, 0x80, 0xa3, 0x77, 0x4d, 0xd1, 0x50,
	0x47, 0xe0, 0xfb, 0xc8, 0xe4, 0x42, 0x97, 0x5b, 0x0d, 0xec, 0x2a, 0xee, 0x48, 0x40, 0xae, 0x27,
	0x14, 0x9a, 0x5c, 0x04, 0xdf, 0xaf, 0xa2, 0xd5, 0xa3, 0x3c, 0xa6, 0xc7, 0x90, 0x0f, 0xd3, 0x08,
	0xf0, 0x18, 0xd9, 0xfd, 0x9c, 0x47, 0x20, 0x65, 0xbf, 0x90, 0xa7, 0xfd, 0x22, 0xcb, 0xf0, 0x7a,
	0x95, 0xd7, 0xd8, 0xf5, 0x25, 0x9c, 0xc5, 0x32, 0x79, 0xf6, 0xf1, 0xc7, 0xef, 0xcf, 0xe6, 0x63,
	0xb2, 0xa7, 0xdf, 0x6f, 0xb8, 0xe7, 0xcf, 0xc6, 0x28, 0xfd, 0x8b, 0x99, 0x31, 0xf6, 0x45, 0x21,
	0x4f, 0x45, 0x91, 0x65, 0xa5, 0x5c, 0xa4, 0xf1, 0xb8, 0x6b, 0x6c, 0xe3, 0x02, 0xdd, 0xac, 0xf1,
	0xbd, 0x2c, 0x05, 0xa6, 0xf0, 0xed, 0x8a, 0x52, 0x59, 0x0d, 0x7a, 0x91, 0x48, 0xba, 0x1a, 0xfc,
	0x88, 0xf8, 0x4b, 0xc1, 0x91, 0xce, 0xbb, 0x8c, 0xbd, 0x98, 0xbd, 0x59, 0x33, 0xc0, 0xa6, 0xed,
	0xb9, 0xe5, 0x71, 0x36, 0xe6, 0xe5, 0xea, 0x89, 0xc9, 0x13, 0x8d, 0x0f, 0xf0, 0xee, 0x52, 0x7c,
	0x5c, 0x13, 0xa4, 0x7f, 0x71, 0x06, 0xa3, 0x31, 0x66, 0x68, 0xad, 0x97, 0x03, 0x55, 0xd0, 0x9b,
	0x2d, 0xdc, 0xdd, 0xba, 0xc3, 0xa9, 0xd2, 0xb4, 0xfe, 0x2f, 0x07, 0x69, 0x6b, 0x3e, 0x71, 0xbc,
	0x65, 0x7c, 0x2c, 0x91, 0x1d, 0x82, 0x04, 0xf5, 0x5f, 0xb8, 0x8e, 0xc6, 0xb5, 0x9d, 0xad, 0xa5,
	0xed, 0xe6, 0x25, 0x0b, 0x9f, 0xa1, 0xf5, 0x13, 0x90, 0xaa, 0xd9, 0xe4, 0xe9, 0x12, 0x36, 0x63,
	0x9e, 0x5b, 0x71, 0x67, 0xb1, 0x4c, 0x1e, 0x68, 0xac, 0x4b, 0xee, 0x35, 0x58, 0x49, 0x07, 0x22,
	0x03, 0xe9, 0xf3, 0xa6, 0x60, 0xd7, 0xd8, 0x3e, 0xe8, 0x7e, 0xda, 0x77, 0xf1, 0x26, 0xda, 0x28,
	0x17, 0xdb, 0x4b, 0xc2, 0x7e, 0xcf, 0x4b, 0xa8, 0x82, 0x0f, 0x74, 0xe4, 0xed, 0xf7, 0x5f, 0xca,
	0xc0, 0x1c, 0xee, 0x7d, 0x9d, 0xb8, 0xc6, 0xb7, 0x89, 0x6b, 0xfc, 0x9c, 0xb8, 0xc6, 0x97, 0x5f,
	0xee, 0x95, 0xd7, 0xd7, 0x3b, 0x4f, 0x07, 0x3c, 0x86, 0xec, 0xed, 0x35, 0xfd, 0xdb, 0x78, 0xf8,
	0x27, 0x00, 0x00, 0xff, 0xff, 0x81, 0x2a, 0xef, 0x16, 0xba, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrdaServiceClient is the client API for OrdaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrdaServiceClient interface {
	ProcessPushPull(ctx context.Context, in *PushPullMessage, opts ...grpc.CallOption) (*PushPullMessage, error)
	ProcessClient(ctx context.Context, in *ClientMessage, opts ...grpc.CallOption) (*ClientMessage, error)
	SnapshotDatatype(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error)
	CreateCollection(ctx context.Context, in *CollectionMessage, opts ...grpc.CallOption) (*CollectionMessage, error)
	ResetCollection(ctx context.Context, in *CollectionMessage, opts ...grpc.CallOption) (*CollectionMessage, error)
	TestEncodingOperation(ctx context.Context, in *EncodingMessage, opts ...grpc.CallOption) (*EncodingMessage, error)
}

type ordaServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrdaServiceClient(cc *grpc.ClientConn) OrdaServiceClient {
	return &ordaServiceClient{cc}
}

func (c *ordaServiceClient) ProcessPushPull(ctx context.Context, in *PushPullMessage, opts ...grpc.CallOption) (*PushPullMessage, error) {
	out := new(PushPullMessage)
	err := c.cc.Invoke(ctx, "/orda.OrdaService/ProcessPushPull", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordaServiceClient) ProcessClient(ctx context.Context, in *ClientMessage, opts ...grpc.CallOption) (*ClientMessage, error) {
	out := new(ClientMessage)
	err := c.cc.Invoke(ctx, "/orda.OrdaService/ProcessClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordaServiceClient) SnapshotDatatype(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	out := new(SnapshotResponse)
	err := c.cc.Invoke(ctx, "/orda.OrdaService/SnapshotDatatype", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordaServiceClient) CreateCollection(ctx context.Context, in *CollectionMessage, opts ...grpc.CallOption) (*CollectionMessage, error) {
	out := new(CollectionMessage)
	err := c.cc.Invoke(ctx, "/orda.OrdaService/CreateCollection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordaServiceClient) ResetCollection(ctx context.Context, in *CollectionMessage, opts ...grpc.CallOption) (*CollectionMessage, error) {
	out := new(CollectionMessage)
	err := c.cc.Invoke(ctx, "/orda.OrdaService/ResetCollection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordaServiceClient) TestEncodingOperation(ctx context.Context, in *EncodingMessage, opts ...grpc.CallOption) (*EncodingMessage, error) {
	out := new(EncodingMessage)
	err := c.cc.Invoke(ctx, "/orda.OrdaService/TestEncodingOperation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrdaServiceServer is the server API for OrdaService service.
type OrdaServiceServer interface {
	ProcessPushPull(context.Context, *PushPullMessage) (*PushPullMessage, error)
	ProcessClient(context.Context, *ClientMessage) (*ClientMessage, error)
	SnapshotDatatype(context.Context, *SnapshotRequest) (*SnapshotResponse, error)
	CreateCollection(context.Context, *CollectionMessage) (*CollectionMessage, error)
	ResetCollection(context.Context, *CollectionMessage) (*CollectionMessage, error)
	TestEncodingOperation(context.Context, *EncodingMessage) (*EncodingMessage, error)
}

// UnimplementedOrdaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrdaServiceServer struct {
}

func (*UnimplementedOrdaServiceServer) ProcessPushPull(ctx context.Context, req *PushPullMessage) (*PushPullMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessPushPull not implemented")
}
func (*UnimplementedOrdaServiceServer) ProcessClient(ctx context.Context, req *ClientMessage) (*ClientMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessClient not implemented")
}
func (*UnimplementedOrdaServiceServer) SnapshotDatatype(ctx context.Context, req *SnapshotRequest) (*SnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SnapshotDatatype not implemented")
}
func (*UnimplementedOrdaServiceServer) CreateCollection(ctx context.Context, req *CollectionMessage) (*CollectionMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCollection not implemented")
}
func (*UnimplementedOrdaServiceServer) ResetCollection(ctx context.Context, req *CollectionMessage) (*CollectionMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetCollection not implemented")
}
func (*UnimplementedOrdaServiceServer) TestEncodingOperation(ctx context.Context, req *EncodingMessage) (*EncodingMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestEncodingOperation not implemented")
}

func RegisterOrdaServiceServer(s *grpc.Server, srv OrdaServiceServer) {
	s.RegisterService(&_OrdaService_serviceDesc, srv)
}

func _OrdaService_ProcessPushPull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushPullMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdaServiceServer).ProcessPushPull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orda.OrdaService/ProcessPushPull",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdaServiceServer).ProcessPushPull(ctx, req.(*PushPullMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrdaService_ProcessClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdaServiceServer).ProcessClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orda.OrdaService/ProcessClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdaServiceServer).ProcessClient(ctx, req.(*ClientMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrdaService_SnapshotDatatype_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdaServiceServer).SnapshotDatatype(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orda.OrdaService/SnapshotDatatype",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdaServiceServer).SnapshotDatatype(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrdaService_CreateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectionMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdaServiceServer).CreateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orda.OrdaService/CreateCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdaServiceServer).CreateCollection(ctx, req.(*CollectionMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrdaService_ResetCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectionMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdaServiceServer).ResetCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orda.OrdaService/ResetCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdaServiceServer).ResetCollection(ctx, req.(*CollectionMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrdaService_TestEncodingOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncodingMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdaServiceServer).TestEncodingOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orda.OrdaService/TestEncodingOperation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdaServiceServer).TestEncodingOperation(ctx, req.(*EncodingMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrdaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "orda.OrdaService",
	HandlerType: (*OrdaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessPushPull",
			Handler:    _OrdaService_ProcessPushPull_Handler,
		},
		{
			MethodName: "ProcessClient",
			Handler:    _OrdaService_ProcessClient_Handler,
		},
		{
			MethodName: "SnapshotDatatype",
			Handler:    _OrdaService_SnapshotDatatype_Handler,
		},
		{
			MethodName: "CreateCollection",
			Handler:    _OrdaService_CreateCollection_Handler,
		},
		{
			MethodName: "ResetCollection",
			Handler:    _OrdaService_ResetCollection_Handler,
		},
		{
			MethodName: "TestEncodingOperation",
			Handler:    _OrdaService_TestEncodingOperation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orda.grpc.proto",
}

func (m *SnapshotRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SnapshotRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SnapshotRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Sseq != 0 {
		i = encodeVarintOrdaGrpc(dAtA, i, uint64(m.Sseq))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Duid) > 0 {
		i -= len(m.Duid)
		copy(dAtA[i:], m.Duid)
		i = encodeVarintOrdaGrpc(dAtA, i, uint64(len(m.Duid)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Collection) > 0 {
		i -= len(m.Collection)
		copy(dAtA[i:], m.Collection)
		i = encodeVarintOrdaGrpc(dAtA, i, uint64(len(m.Collection)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintOrdaGrpc(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SnapshotResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SnapshotResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SnapshotResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Json) > 0 {
		i -= len(m.Json)
		copy(dAtA[i:], m.Json)
		i = encodeVarintOrdaGrpc(dAtA, i, uint64(len(m.Json)))
		i--
		dAtA[i] = 0x12
	}
	if m.Meta != nil {
		{
			size, err := m.Meta.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOrdaGrpc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EncodingMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EncodingMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EncodingMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Op != nil {
		{
			size, err := m.Op.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOrdaGrpc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Type != 0 {
		i = encodeVarintOrdaGrpc(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintOrdaGrpc(dAtA []byte, offset int, v uint64) int {
	offset -= sovOrdaGrpc(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SnapshotRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovOrdaGrpc(uint64(l))
	}
	l = len(m.Collection)
	if l > 0 {
		n += 1 + l + sovOrdaGrpc(uint64(l))
	}
	l = len(m.Duid)
	if l > 0 {
		n += 1 + l + sovOrdaGrpc(uint64(l))
	}
	if m.Sseq != 0 {
		n += 1 + sovOrdaGrpc(uint64(m.Sseq))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SnapshotResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Meta != nil {
		l = m.Meta.Size()
		n += 1 + l + sovOrdaGrpc(uint64(l))
	}
	l = len(m.Json)
	if l > 0 {
		n += 1 + l + sovOrdaGrpc(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *EncodingMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovOrdaGrpc(uint64(m.Type))
	}
	if m.Op != nil {
		l = m.Op.Size()
		n += 1 + l + sovOrdaGrpc(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovOrdaGrpc(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOrdaGrpc(x uint64) (n int) {
	return sovOrdaGrpc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SnapshotRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrdaGrpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SnapshotRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SnapshotRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrdaGrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrdaGrpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOrdaGrpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Collection", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrdaGrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrdaGrpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOrdaGrpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Collection = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrdaGrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrdaGrpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOrdaGrpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Duid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sseq", wireType)
			}
			m.Sseq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrdaGrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sseq |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOrdaGrpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOrdaGrpc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthOrdaGrpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SnapshotResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrdaGrpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SnapshotResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SnapshotResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Meta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrdaGrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrdaGrpc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOrdaGrpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Meta == nil {
				m.Meta = &DatatypeMeta{}
			}
			if err := m.Meta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Json", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrdaGrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrdaGrpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOrdaGrpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Json = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOrdaGrpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOrdaGrpc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthOrdaGrpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EncodingMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrdaGrpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EncodingMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EncodingMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrdaGrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= TypeOfDatatype(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Op", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrdaGrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrdaGrpc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOrdaGrpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Op == nil {
				m.Op = &Operation{}
			}
			if err := m.Op.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOrdaGrpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOrdaGrpc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthOrdaGrpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOrdaGrpc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOrdaGrpc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOrdaGrpc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOrdaGrpc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthOrdaGrpc
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupOrdaGrpc
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthOrdaGrpc
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthOrdaGrpc        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOrdaGrpc          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupOrdaGrpc = fmt.Errorf("proto: unexpected end of group")
)
